### ISSUE TITLE
AttributeError: 'UnixDomainSocketConnection' object has no attribute '_buffer_cutoff'

### ISSUE THREAD

**Issue by torhn** [andymccurdy/redis-py#1067]
Since version 3.0, redis client seems broken. I cannot even get, set or keys() anything when connecting to unix socket.
I tried running it in a docker container running centos 7.5.1804 core using python3.6.
Steps to reproduce:
 install redis 3.0
```python
import redis
red = redis.Redis(unix_socket_path = "/path/to/socket")
red.keys()
```
Throws this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 1262, in keys
    return self.execute_command('KEYS', pattern)
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python3.6/site-packages/redis/connection.py", line 658, in pack_command
    buffer_cutoff = self._buffer_cutoff
AttributeError: 'UnixDomainSocketConnection' object has no attribute '_buffer_cutoff'
```

**Comment by olemoign** [comment]
Same problem for me, on both macOS Mojave 10.14.1 and Ubuntu 16.04.
