### ISSUE TITLE
zadd with xx and incr crashes when key doesn't exist

### ISSUE THREAD

**Issue by bucko909** [andymccurdy/redis-py#1084]
Test case (should work on empty redis):

```
>>> r.zadd("this key does exist", {"this key will exist": 1})
1
>>> r.zadd("this key does exist", {"this does exist": 1})
1
>>> r.zadd("this key does exist", {"this does exist": 1}, xx=True)
0
>>> r.zadd("this key does exist", {"this does exist": 1}, xx=True, incr=True)
2.0
>>> r.zadd("this key does exist", {"this does not exist": 1}, xx=True)
0
>>> r.zadd("this key does exist", {"this does not exist": 1}, xx=True, incr=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bucko/tmpenv/local/lib/python2.7/site-packages/redis/client.py", line 2266, in zadd
    return self.execute_command('ZADD', name, *pieces, **options)
  File "/home/bucko/tmpenv/local/lib/python2.7/site-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/bucko/tmpenv/local/lib/python2.7/site-packages/redis/client.py", line 774, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "/home/bucko/tmpenv/local/lib/python2.7/site-packages/redis/client.py", line 307, in parse_zadd
    return float(response)
TypeError: float() argument must be a string or a number
```

The response in this case is a nil, I think, which isn't `float()`able.

This may be a redis bug; I can't actually find anything in the documentation indicating what the return value should be. It should be a bulk string reply, referring to `ZINCRBY` for docs -- but `ZINCRBY` doesn't support `XX`. Either way there's no actual spec and redis *does* return a nil value here:

```
127.0.0.1:6379> zadd "this key does exist" XX INCR 1 "dfsdfas"
(nil)
127.0.0.1:6379> zadd "this key does exist" XX INCR 1 "this does exist"
"2"
```

**Comment by itamarhaber** [comment]
Hello @bucko909 

Thanks for reporting this issue.

Despite the lack of documentation, this does not appear to be a Redis bug and the nil response makes sense imo as it signals the caller that the increment did not happen. That being the case, the documentation could be improved to explain that (https://github.com/antirez/redis-doc/pull/1042).

**Comment by andymccurdy** [comment]
ZADD now returns `None` in this case. Thanks for reporting this.

**Comment by bucko909** [comment]
Cool, thanks for fixing. :)
