### ISSUE TITLE
Redis + sentinel connection infinite loop

### ISSUE THREAD

**Issue by drivefast** [andymccurdy/redis-py#1144]
Hi there. Here are the basics:
- redis-py ver 3.2.0 with a redis ver 5.0.3
- python 2.7.5 on centos 7
- nginx + uwsgi
When uwsgi is started, i define the redis connections and quickly do a health check (write a key, read it back). That works fine. However, the first redis operation resulted from an http request to the server throws the driver into a continuous connection reattempt loop. See below. Note the connection is going via a Sentinel driver. Downgrading to redis-py 2.10.6 fixed the issue for now.

Any thoughts much appreciated!

```Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "./models/agent.py", line 26, in request_wrapper
    d = rdb.hgetall("some_key_name")
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 2649, in hgetall
    return self.execute_command('HGETALL', name)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 986, in get_connection
    self._checkpid()
  File "/usr/lib/python2.7/site-packages/redis/sentinel.py", line 130, in _checkpid
    self.disconnect()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 1037, in disconnect
    self._checkpid()
  File "/usr/lib/python2.7/site-packages/redis/sentinel.py", line 130, in _checkpid
    self.disconnect()

..................

  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 1037, in disconnect
    self._checkpid()
  File "/usr/lib/python2.7/site-packages/redis/sentinel.py", line 130, in _checkpid
    self.disconnect()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 1037, in disconnect
    self._checkpid()
RuntimeError: maximum recursion depth exceeded
```

**Comment by lxserenade** [comment]
same issue here

**Comment by drivefast** [comment]
@lxserenade if you have a way to reproduce it, or some more details, maybe you can post here?... There is only one point where i see this constantly happening in my code, and i havent been able to extract an example properly. Thanks.

**Comment by unbeatedkb** [comment]
In addition to it.
Using os.fork to fork a child will cause this problem, such as 
![image](https://user-images.githubusercontent.com/18637307/54004514-bc31ff00-4190-11e9-950d-2673224630ae.png)
And I check code, as you can see in the pic below.
Obviously, it was caused by this code.
![image](https://user-images.githubusercontent.com/18637307/54004672-6a3da900-4191-11e9-8a90-24225809f64e.png)
![image](https://user-images.githubusercontent.com/18637307/54004684-7c1f4c00-4191-11e9-80f4-342b01e6b6fe.png)

**Comment by WoLpH** [comment]
I don't have an easily reproducible example but I'm experiencing the same when using a forking celery worker and a sentinel connection defined in the root of one of the files. Can't say I've done much debugging yet but downgrading to version 3.1.0 with kombu 4.1.0 I got it working again.

**Comment by andymccurdy** [comment]
Can someone with this problem try running the `sentinel_pool_fix` branch (https://github.com/andymccurdy/redis-py/tree/sentinel_pool_fix) and see if you still get the same errors?

**Comment by WoLpH** [comment]
Seems to work great for me @andymccurdy 

Thanks for the quick fix!

**Comment by andymccurdy** [comment]
Great, thanks @WoLpH. I'll get this fix out in a pypi release shortly.

**Comment by andymccurdy** [comment]
3.2.1 is out with this fix.
