### ISSUE TITLE
Behaviour of 'encoding_errors' differs when hiredis-py is installed

### ISSUE THREAD

**Issue by candlerb** [andymccurdy/redis-py#1161]
**Version**: redis-py 3.2.1 installed using pip; redis 5.0.4 built from source; (optionally) hiredis-py 1.0.0 built from from source

**Platform**: python 3.6.7 on Ubuntu 18.04

**Description**:

When hiredis-py is not installed, `encoding_errors` behaves as expected:

```
root@redis:~# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> r = redis.Redis(decode_responses=True, encoding_errors="replace")
>>> r.set("foo",b"bar\xff")
True
>>> r.get("foo")
'bar�'
>>> r = redis.Redis(decode_responses=True, encoding_errors="ignore")
>>> r.get("foo")
'bar'
>>>
```

However, when hiredis-py is available, it behaves differently, and the `encoding_errors` option doesn't appear to make any difference:

```
>>> r = redis.Redis(decode_responses=True, encoding_errors="replace")
>>> r.get("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1264, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 414, in read_response
    response = self._reader.gets()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 3: invalid start byte
>>> r = redis.Redis(decode_responses=True, encoding_errors="ignore")
>>> r.get("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1264, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 414, in read_response
    response = self._reader.gets()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 3: invalid start byte
>>>
```

It appears that the `errors` option is not being passed to `hiredis.Reader`

**Comment by candlerb** [comment]
Note: the behaviour I saw with older versions of hiredis-py when used with redis-py and `decode_responses=True` was that non-decodable UTF-8 was being returned as `bytes` instead of `str`
