### ISSUE TITLE
Docker network socket timeout

### ISSUE THREAD

**Issue by wshayes** [andymccurdy/redis-py#1203]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
redis-py:  3.3.7
redis: 5.0.5
Docker version 19.03.1
docker-compose version 1.24.1

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python 3.7 on MacOS and Ubuntu (both running in docker)

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

Using the following client setup while trying to use BRPOPLPUSH to wait for new tasks to show up.

```
redis_db = redis.Redis(
    host=settings.REDIS_HOST,
    port=settings.REDIS_PORT,
    db=0,
    health_check_interval=30,
    socket_keepalive=True,
    socket_timeout=60,
    retry_on_timeout=True,
)
```

I'm getting the following timeout which is causing the docker container to restart.  I'm starting several multiprocessing.Process to take jobs off of the task queue. I don't get the timeouts when I run this code outside of docker. Any suggestions on best way to handle this?  I looked at the other issues that had socket timeouts and tried everything I understood and several things I didn't (obviously since I have practically every socket/keepalive option turned on).

```
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 538, in connect
pipeline           |     sock = self._connect()
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 595, in _connect
pipeline           |     raise err
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 583, in _connect
pipeline           |     sock.connect(socket_address)
pipeline           | socket.timeout: timed out
pipeline           |
pipeline           | During handling of the above exception, another exception occurred:
pipeline           |
pipeline           | Traceback (most recent call last):
pipeline           |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
pipeline           |     self.run()
pipeline           |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
pipeline           |     self._target(*self._args, **self._kwargs)
pipeline           |   File "./main.py", line 95, in process_tasks
pipeline           |     for worker_qname, task_str in db.redisdb.yield_queue(store, worker_id):
pipeline           |   File "/app/db/redisdb.py", line 44, in yield_queue
pipeline           |     task = redis_db.brpoplpush(store_qname, worker_qname, 0)
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1648, in brpoplpush
pipeline           |     return self.execute_command('BRPOPLPUSH', src, dst, timeout)
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 836, in execute_command
pipeline           |     conn = self.connection or pool.get_connection(command_name, **options)
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1071, in get_connection
pipeline           |     connection.connect()
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 540, in connect
pipeline           |     raise TimeoutError("Timeout connecting to server")
pipeline           | redis.exceptions.TimeoutError: Timeout connecting to server
pipeline           | Traceback (most recent call last):
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 538, in connect
pipeline           |     sock = self._connect()
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 595, in _connect
pipeline           |     raise err
pipeline           |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 583, in _connect
pipeline           |     sock.connect(socket_address)
pipeline           | socket.timeout: timed out
```

**Comment by wshayes** [comment]
I'm wrapping every call to redis in something like the following (a try/except to reconnect on Timeout.  Is this the right approach? Is there a better way to handle this? 

```
    while True:
        try:
            log.info("Trying to get task", store=store_qname)
            task = redis_db.brpoplpush(store_qname, worker_qname, 0)
            log.info("Yielding task", task=task)
            yield worker_qname, task
        except redis.exceptions.TimeoutError:
            redis_db = get_redis_client()
```

**Comment by andymccurdy** [comment]
You're specifying a `socket_timeout` and using blocking commands with an indefinite timeout. This combination means that after 60 seconds of waiting for an item, Python will raise a `socket.timeout`.

Instead, specify a timeout to the `BRPOPLPUSH` command that's smaller than the overall `socket_timeout`. Then check the return value of the `BRPOPLPUSH`. If the return value is `None`, that means the timeout was hit and no task was found. In this case, just re-enter your loop.

```python
redis_db = redis.Redis(
    host=settings.REDIS_HOST,
    port=settings.REDIS_PORT,
    db=0,
    health_check_interval=30,
    socket_keepalive=True,
    socket_timeout=60,
    retry_on_timeout=True,
)

while True:
    task = redis_db.brpoplpush(store_qname, worker_qname, 30)  # 30 second timeout is < 60
    if task is None:
        continue
    # got a task, process it
```

**Comment by wshayes** [comment]
Thank you!
