### ISSUE TITLE
Tuple index out of range, in HGET, HSET while using functions in threading.Thread

### ISSUE THREAD

**Issue by leexxg** [andymccurdy/redis-py#1207]
Hi, 

**Version**: redis-cli v.4.0.9/redis-py 3.3.8

**Platforms**: Ubuntu 18.04/Windows 7(x64)

**Language**: Python 3.6

**Description**: I have small redis code, with 2 functions

```
import redis
def connect_to_redis(redis_host = "127.0.0.1", redis_port = 6379, db=0, password = None):
    try:
        redis_connection = redis.StrictRedis(host=redis_host, port=redis_port, db=db, password=password)
       return redis_connection
    except Exception as e:
        print("--REDIS: ERROR: Can't connect to {}:{} - {}".format(redis_host, redis_port, e))
        return False

def get_error_from_redis(wallet_id, error_type):
    try:
        redis_connection = connect_to_redis()
        if redis_connection==False:
            return False

        try:
            errors_list = redis_connection.hget(name = wallet_id, key = error_type) # ERROR HERE
        except Exception as e:
            print("-- REDIS ERROR(get_error_from_redis): with wallet_id:{}, error_type:{} - {}".format(wallet_id, error_type, e))

        if errors_list:
            errors_list = errors_list.decode('utf-8')
            errors_list = ast.literal_eval(errors_list)
            #print("-- REDIS GET(for wallet_id) - {}".format(len(errors_list)))
            if errors_list!=None:
                #print("-- REDIS GET (for wallet_id:{}, error_type:{}) - {}".format(wallet_id, error_type, len(errors_list)))
                return errors_list

        print("-- REDIS ERRORS LIST EMPTY FOR: wallet_id: {}".format(wallet_id))
        return []
    except Exception as e:
        print("-- REDIS ERROR(get_error_from_redis): with wallet_id:{}, error_type:{} - {}".format(wallet_id, error_type, e))
        return False
```

When i make tests in main(in this file) - everything is ok, But when i import this functions into logic, where i use threading.Thread(with 1 thread only), then i got error(for line - redis_connection.hget(name = wallet_id, key = error_type)) - tuple index out of range. I checked that redis_connection is ok(Redis<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>) and checked that i had those variables - wallet_id(type str) and error_type(type str) inside of function). How i even can get this type of error in HGET?

**Comment by leexxg** [comment]
Traceback (most recent call last):
  File "/var/www/proccessing/errors/errors_redis_class.py", line 102, in get_error_from_redis
    errors_list = r.hget(wallet_id, error_type)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 2713, in hget
    return self.execute_command('HGET', name, key)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 1071,in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 543, in connect
    raise ConnectionError(self._error_message(e))
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 606, in _error_message
    (exception.args[0], self.host, self.port, exception.args[1])
IndexError: tuple index out of range

**Comment by leexxg** [comment]
Version of redis-py 3.3.8

**Comment by leexxg** [comment]
Finally, here's roots of my problem: 
socks.setdefaultproxy() and then
socket.socket = socks.socksocket - to read emails, and this one is set socket with proxy value. 
If i skip that part, i connect to redis and everything is ok(i just checked that), and i actually can do this(so all issue will be solved). But i just still intrested with, is it possible, to connect to redis, with skipping/ignoring this socket?
