### ISSUE TITLE
Celery Backend connection with Redis 3.3.8 error

### ISSUE THREAD

**Issue by srivignessh** [andymccurdy/redis-py#1223]
Version: 3.3.8
Platform: python 2.7 on ubuntu

```
[2019-10-09 23:49:35,629: ERROR/CeleryWorkerProcess-25] Unrecoverable error: AttributeError("'unicode' object has no attribute 'iteritems'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 340, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 991, in on_readable
    self._callbacks[queue](message)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 534, in _callback
    self.qos.append(message, message.delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 146, in append
    pipe.zadd(self.unacked_index_key, delivery_tag, time()) \
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2388, in zadd
    for pair in iteritems(mapping):
  File "/usr/local/lib/python2.7/dist-packages/redis/_compat.py", line 81, in iteritems
    return x.iteritems()
AttributeError: 'unicode' object has no attribute 'iteritems'
[2019-10-09 23:49:35,646: INFO/MainProcess] beat: Shutting down...
```

Celery worker not starting because of the above error.

**Comment by andymccurdy** [comment]
Looks like you have an old version of kombu. Upgrade to the latest version.

**Comment by andymccurdy** [comment]
Closing this as there's been no response. Please reopen if it's still an issue after upgrading kombu.
