### ISSUE TITLE
Redis model does not implement __hash__.

### ISSUE THREAD

**Issue by Domol** [andymccurdy/redis-py#1275]
**Version**: 3.4.0

**Platform**: Python 3.7

**Description**: 
in the new version Redis model has `__eq__` implemented but not `__hash__`.
Python docs(https://docs.python.org/3/reference/datamodel.html#object.__hash):

> if it defines eq() but not hash(), its instances will not be usable as items in hashable collections.

> A class that overrides __eq__() and does not define __hash__() will have its __hash__() implicitly set to None. When the __hash__() method of a class is None, instances of the class will raise an appropriate TypeError when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking isinstance(obj, collections.abc.Hashable).

> If a class that overrides __eq__() needs to retain the implementation of __hash__() from a parent class, the interpreter must be told this explicitly by setting __hash__ = <ParentClass>.__hash__.

Shouldn't Redis implement `__hash__` then?

There is an issue with `kombu` related to it: https://github.com/celery/kombu/issues/1152

**Comment by dominik-bln** [comment]
We are encountering the same problem when updating our Celery workers from `3.3.11` to `v3.4.0`:

```bash
[2020-01-31 12:22:49,722: CRITICAL/MainProcess] Unrecoverable error: TypeError("unhashable type: 'Redis'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/mingle.py", line 40, in start
    self.sync(c)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/mingle.py", line 44, in sync
    replies = self.send_hello(c)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/mingle.py", line 57, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/usr/local/lib/python3.7/site-packages/celery/app/control.py", line 154, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/usr/local/lib/python3.7/site-packages/celery/app/control.py", line 106, in _request
    pattern=self.pattern, matcher=self.matcher,
  File "/usr/local/lib/python3.7/site-packages/celery/app/control.py", line 477, in broadcast
    limit, callback, channel=channel,
  File "/usr/local/lib/python3.7/site-packages/kombu/pidbox.py", line 352, in _broadcast
    channel=chan)
  File "/usr/local/lib/python3.7/site-packages/kombu/pidbox.py", line 391, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 323, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 963, in drain_events
    get(self._deliver, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 374, in get
    self._register_BRPOP(channel)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 311, in _register_BRPOP
    if not self._client_registered(channel, channel.client, 'BRPOP'):
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 306, in _client_registered
    (channel, client, cmd) in self._chan_to_sock)
TypeError: unhashable type: 'Redis'
```

**Comment by CoDanny** [comment]
This seems to be an API change in this library. Even though no part of the call stack is in it. Simply downgrading the library makes the problem go away.

**Comment by andymccurdy** [comment]
I'll have this fixed later today including a 3.4.1 release.

**Comment by k0nG** [comment]
Thanks @andymccurdy for releasing a fix so quickly. All good for me with Celery 4.4.0

**Comment by dominik-bln** [comment]
Yes, thank you! I can also confirm that the problem is fixed.
