### ISSUE TITLE
3.4.0 changed argument positions for constructor

### ISSUE THREAD

**Issue by bmerry** [andymccurdy/redis-py#1276]
**Version**: redis-py 3.4.0, redis 4.0.9

**Platform**: Python 3.6.6, Ubuntu 18.04

**Description**: Version 3.4.0 added an extra `username` argument to the `redis.Redis` constructor, but because it was added near the front of the list, and the arguments are not marked keyword-only, it breaks code that passes arguments to the constructor positionally.

Here's a (somewhat contrived) example, that works on 3.3.11 but breaks on 3.4.0. This is the cause of jamesls/fakeredis#260.

```python3
#!/usr/bin/env python3
import redis

r = redis.Redis('localhost', 6379, 0, None, None, None, None, None, None, None, 'utf-8')
print(r.ping())
```

On 3.4.0 the 'utf-8' gets interpreted as `unix_socket_path` instead of `encoding`, leading to
```
Traceback (most recent call last):
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/redis/connection.py", line 550, in connect
    sock = self._connect()
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/redis/connection.py", line 892, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bad2.py", line 5, in <module>
    print(r.ping())
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/redis/client.py", line 1357, in ping
    return self.execute_command('PING')
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/redis/client.py", line 881, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/redis/connection.py", line 1178, in get_connection
    connection.connect()
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/redis/connection.py", line 555, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: utf-8. No such file or directory.
```

**Comment by andymccurdy** [comment]
I moved the username arg to the end of the list in 5a1f3c4. 3.4.1 will be published shortly.

**Comment by bmerry** [comment]
Thanks!

**Comment by paltman** [comment]
I'm still seeing this: 

Clipped for brevity but getting into Redis through Django/RQ:

```../.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/rq/queue.py:424: in enqueue_job
    pipe.execute()
../.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/redis/client.py:3961: in execute
    self.shard_hint)
../.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/redis/connection.py:1185: in get_connection
    connection.connect()
../.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/fakeredis/_server.py:2527: in connect
    super(FakeConnection, self).connect()
../.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/redis/connection.py:561: in connect
    self.on_connect()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'FakeConnection' object has no attribute 'host'",) raised in repr()] FakeConnection object at 0x7f1df0c616a0>

    def on_connect(self):
        "Initialize the connection, authenticate and select a database"
        self._parser.on_connect(self)
    
        # if username and/or password are set, authenticate
>       if self.username or self.password:
E       AttributeError: 'FakeConnection' object has no attribute 'username'

../.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/redis/connection.py:627: AttributeError
```

**Comment by andymccurdy** [comment]
This seems like a FakeRedis issue?

**Comment by paltman** [comment]
Yeah you are right. I think there is a release coming this week on that library to fix this.

**Comment by bmerry** [comment]
Yes, it's a fakeredis issue, and I'm hoping to get a fix out this week.
