### ISSUE TITLE
spop test fails on redis server 3.0.x

### ISSUE THREAD

**Issue by Grokzen** [andymccurdy/redis-py#1298]
**Version**: What redis-py and what redis version is the issue happening on?

 - 3.4.x

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)

 - Ubuntu 19.10, python 3.8

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

Test method `test_spop_multi_value` fails when running the test suite against a redis server with version 3.0.7

Steps to reproduce

```
>>> from redis import Redis                                     
                                                                
>>> r = Redis(host='localhost', port=7002)                      
                                                                
>>> r                                                           
Redis<ConnectionPool<Connection<host=localhost,port=7002,db=0>>>

>>> r.spop('a', count=2)                                                                                                              
Traceback (most recent call last):                                                                                              
  File "<stdin>", line 1, in <module>                                                                                           
  File "/home/grok/.virtualenvs/redis-py-cluster-38/lib/python3.8/site-packages/redis/client.py", line 2255, in spop            
    return self.execute_command('SPOP', name, *args)                                                                            
  File "/home/grok/.virtualenvs/redis-py-cluster-38/lib/python3.8/site-packages/redis/client.py", line 878, in execute_command  
    return self.parse_response(conn, command_name, **options)                                                                   
  File "/home/grok/.virtualenvs/redis-py-cluster-38/lib/python3.8/site-packages/redis/client.py", line 892, in parse_response   
    response = connection.read_response()                                                                                       
  File "/home/grok/.virtualenvs/redis-py-cluster-38/lib/python3.8/site-packages/redis/connection.py", line 752, in read_response
    raise response                                                                                                              
redis.exceptions.ResponseError: wrong number of arguments for 'spop' command                                                    
                                                                                                                                
wrong number of arguments for 'spop' command          
```

```
>>> r.info()                            
{'redis_version': '3.0.7', ... }
```

# Reason

According to official redis.io docs it says this about the count argument added to `spop`

```
Count argument extension
Redis 3.2 introduced an optional count argument that can be passed to SPOP in order to retrieve multiple elements in a single call.
```

# Solution
Should be fairly simple, add `@skip_if_server_version_lt('3.2.0')` to the method `test_spop_multi_value`

**Comment by andymccurdy** [comment]
Thanks, fixed in master.
