### ISSUE TITLE
redis.exceptions.ResponseError: unknown command 'ZPOPMAX'

### ISSUE THREAD

**Issue by Pradipta234** [andymccurdy/redis-py#1368]
**Version**: redis-3.5.3

**Platform**: Python 3.7.3 (default, Apr  3 2019, 19:16:38) on Ubuntu16.04

**Description**:

This is the code snippet

>>> import redis
>>> pool = redis.ConnectionPool(host='localhost', port=6379, db=0)
>>> r = redis.Redis(connection_pool=pool)
>>> r.zincrby('queue',2,'hello')
2.0
>>> r.zincrby('queue',2,'hello')
4.0
>>> r.zincrby('queue',1,'he')
1.0
>>> r.zpopmax('queue')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pradipta/.local/lib/python3.7/site-packages/redis/client.py", line 2729, in zpopmax
    return self.execute_command('ZPOPMAX', name, *args, **options)
  File "/home/pradipta/.local/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/pradipta/.local/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/pradipta/.local/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'ZPOPMAX'

**Comment by andymccurdy** [comment]
The server you're connecting to doesn't have the `ZPOPMAX` command. According to the docs (https://redis.io/commands/zpopmax), you need Redis server version 5.0 or greater.

**Comment by Pradipta234** [comment]
Issue Resolved. Thanks a lot.
