### ISSUE TITLE
When the return value from the execute command is a string, library is complaining for an int value

### ISSUE THREAD

**Issue by RohanMajumdar69** [andymccurdy/redis-py#1370]
**Version**: redis-py version 3.5.3 and redis 5.0.8

Python 3.6 on  Ubuntu 18.04

r.execute_command("REPLICAOF", str(address), port)
  File "/home/amni-user2/Documents/Project/venv/lib/python3.6/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/amni-user2/Documents/Project/venv/lib/python3.6/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/amni-user2/Documents/Project/venv/lib/python3.6/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: value is not an integer or out of range

**Comment by andymccurdy** [comment]
The `REPLICAOF` command syntax is `REPLICAOF <host> <port>`. You have the host and port swapped.

**Comment by RohanMajumdar69** [comment]
Ohhh sorry that is an experiment that I did while I was debugging but trust me the result is the same.
First I tried it with address first and then I tried with port first to see whether that is working based on an internet post.
It does not have any bearing on the outcome. It remains the same.

**Comment by mondeja** [comment]
I can't reproduce it with `redis-py==3.5.3`:

```python
>>> r.execute_command("REPLICAOF", "localhost", 6379)
b'OK'
>>> r.execute_command("REPLICAOF", 6379, "locahost")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mondeja/files/code/smartgis/env/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/mondeja/files/code/smartgis/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/mondeja/files/code/smartgis/env/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: value is not an integer or out of range
>>> r.execute_command("REPLICAOF", str(6379), "locahost")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mondeja/files/code/smartgis/env/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/mondeja/files/code/smartgis/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/mondeja/files/code/smartgis/env/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: value is not an integer or out of range
>>> r.execute_command("REPLICAOF", str(6379), 6379)
b'OK'
```

**Comment by andymccurdy** [comment]
@RohanMajumdar69 I would suggest trying again.  Looks like it worked for @mondeja

**Comment by RohanMajumdar69** [comment]
I think it is working now. There was a defect n my script only. Sorry for the false alarm.

**Comment by RohanMajumdar69** [comment]
And I forgot to thank you. Stay safe brother.
