### ISSUE TITLE
When the concurrency is large, the connection pool efficiency is very low！

### ISSUE THREAD

**Issue by MakeYuan-Driver** [andymccurdy/redis-py#1372]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
3.5.3

**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Ubuntu 15.10

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
We Have A RedisSentinel Cluser, Service  Config MaxConnection=50,About 300 pods, Redis Master Most Ops About 30000/s
,Probably only handle 2 ～3 requests per connection，But Client  Rasie Error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/python3.6/site-packages/redis/client.py", line 3010, in hget
    return self.execute_command('HGET', name, key)
  File "lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/lib/python3.6/site-packages/redis/connection.py", line 1187, in get_connection
    connection = self.make_connection()
  File "./lib/python3.6/site-packages/redis/connection.py", line 1225, in make_connection
    raise ConnectionError("Too many connections")
redis.exceptions.ConnectionError: Too many connections
```
So I Debug Test 
```
def main():
	sentinel,client = redis_sentinel_url.connect(testurl,client_class=redis.Redis,sentinel_options=sentinel_connection_kwargs,client_options=client_connection_kwargs)
	i=1
	t1=time.time()+60
	while time.time()<t1:
		while i <=100:
			threads=[]
			for  index in range(i*10):
				#threads.append(threading.Thread(target=workping,args=(client)))
				threads.append(threading.Thread(target=client.ping))
			for x in  threads:
				x.start()
			for x in threads:
				x.join()
			i=i+1
		while i <=50:
			threads=[]
			for  index in range(i*10):
                        	#threads.append(threading.Thread(target=workping,args=(client)))
                        	threads.append(threading.Thread(target=client.ping))
			for x in  threads:
				x.start()
			for x in threads:
				x.join()
```
Result:

```
   155051002 function calls (155050460 primitive calls) in 60.059 seconds
152943882   16.717    0.000   16.717    0.000 {built-in method time.time}
   252502    6.617    0.000    6.617    0.000 {method 'acquire' of '_thread.lock' objects}
   101136    0.029    0.000    0.029    0.000 {built-in method _thread.allocate_lock}
   101127    0.012    0.000    0.012    0.000 {built-in method _thread.get_ident}
   101000    0.033    0.000    0.045    0.000 threading.py:1230(current_thread)
   101000    0.027    0.000    0.027    0.000 threading.py:506(is_set)
   101000    0.014    0.000    0.014    0.000 {method 'release' of '_thread.lock' objects}
    51755    0.008    0.000    0.008    0.000 {method 'append' of 'list' objects}
    50716    0.009    0.000    0.009    0.000 {method 'add' of 'set' objects}
    50501    0.155    0.000    0.471    0.000 threading.py:757(__init__)
    50501    0.148    0.000    0.148    0.000 threading.py:215(__init__)
    50501    0.058    0.000    0.216    0.000 threading.py:498(__init__)
    50501    0.035    0.000    0.052    0.000 threading.py:239(__enter__)
    50501    0.035    0.000    0.043    0.000 _weakrefset.py:81(add)
    50501    0.026    0.000    0.034    0.000 threading.py:242(__exit__)
    50501    0.023    0.000    0.041    0.000 threading.py:254(_is_owned)
    50501    0.018    0.000    0.018    0.000 {method '__enter__' of '_thread.lock' objects}
    50501    0.008    0.000    0.008    0.000 {method '__exit__' of '_thread.lock' objects}
    50500    0.556    0.000    0.556    0.000 {built-in method _thread.start_new_thread}
````

**Comment by andymccurdy** [comment]
Are you specifying `max_connections` when you're creating the `ConnectionPool`? The "Too Many Connections" error message is raised when the connection pool tried to create more connections than the `max_connections` limit. Either raise the `max_connections` value or reduce the number of threads.

I'm not entirely sure what your profile is getting at. What were you expecting to see?

**Comment by MakeYuan-Driver** [comment]
I don't have an opinion on "Too Many Connections",I'm just curious large concurrency,Maybe to `get_connection` spend lot of time,But did nothing

**Comment by andymccurdy** [comment]
How many threads are attempting to use the connection pool? How many requests / second are you able to achieve? Is it actually slow or are you simply maxing our your system?

An arbitrary profile doesn’t provide much information without context.

**Comment by andymccurdy** [comment]
Closing this as no more information was provided. If you're still having issues, feel free to re-open and provide additional information about what's going on.
