### ISSUE TITLE
redis.exceptions.ResponseError: unknown command 'INFO'

### ISSUE THREAD

**Issue by hellvix** [andymccurdy/redis-py#1381]
**Version**: 1.5

**Platform**: Ubuntu 18

**Description**: 

I started to get the following error after I upgraded from version 1.4.2 to 1.5. Has anyone faced a similar problem?

```
Traceback (most recent call last):
  File "/home/projects/sources/atom/bin/mail.py", line 85, in dispatch
    queue_job(
  File "/home/projects/sources/atom/bin/tasks.py", line 83, in queue_job
    raise e
  File "/home/projects/sources/atom/bin/tasks.py", line 77, in queue_job
    return queue.enqueue(func, args=args, ttl=ttl)
  File "/home/projects/environments/penv/lib/python3.8/site-packages/rq/queue.py", line 421, in enqueue
    return self.enqueue_call(
  File "/home/projects/environments/penv/lib/python3.8/site-packages/rq/queue.py", line 368, in enqueue_call
    job = self.enqueue_job(job, at_front=at_front)
  File "/home/projects/environments/penv/lib/python3.8/site-packages/rq/queue.py", line 476, in enqueue_job
    job.save(pipeline=pipe)
  File "/home/projects/environments/penv/lib/python3.8/site-packages/rq/job.py", line 585, in save
    if self.get_redis_server_version() >= StrictVersion("4.0.0"):
  File "/home/projects/environments/penv/lib/python3.8/site-packages/rq/job.py", line 594, in get_redis_server_version
    self.connection.info("server")["redis_version"]
  File "/home/projects/environments/penv/lib/python3.8/site-packages/redis/client.py", line 1306, in info
    return self.execute_command('INFO', section)
  File "/home/projects/environments/penv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/projects/environments/penv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/projects/environments/penv/lib/python3.8/site-packages/fakeredis/_server.py", line 2663, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'INFO'
```

```
$ redis-server --version
Redis server v=6.0.1 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=0
```

**Comment by hellvix** [comment]
The problem seemed to be with `rq`. They patched to version 1.5.1 and the problem was solved.
