### ISSUE TITLE
Redis SERVER_CLOSED_CONNECTION_ERROR preventing long-running PubSub subscription

### ISSUE THREAD

**Issue by nswimmer** [andymccurdy/redis-py#1404]
**Version**:
redis-py: 3.5.3
redis: 6.0.8
python: 3.8.5

**Platform**:
Ubuntu 20.04 LTS

**Description**:
I'm attempting to use pubsub to listen for messages indefinitely in a program, but it appears that the redis connection is being closed by the server periodically every few minutes. The initial code I've been using to test this is as follows (called redisTest.py)

```
import logging
import redis
import time

if __name__ == "__main__":
    log = logging.getLogger(__name__)
    logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(message)s')

    r = redis.Redis(host='127.0.0.1', port=6379, db=0, socket_timeout=None, socket_keepalive=True)

    ps = r.pubsub()
    ps.subscribe("test-channel")

    while True:
        msg = ps.get_message()
        if msg:
            log.info(f"Pubsub received: {msg}")
        else:
            pass
        time.sleep(0.01)
```

When this code is run, it results in the following behavior about 3 minutes later 

```
2020-09-24 11:57:49,988 - Pubsub received: {'type': 'subscribe', 'pattern': None, 'channel': b'test-channel', 'data': 1}
Traceback (most recent call last):
  File "redisTest.py", line 15, in <module>
    msg = ps.get_message()
  File "/home/anaconda3/lib/python3.7/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/anaconda3/lib/python3.7/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 417, in can_read
    raise_on_timeout=False)
  File "/home/anaconda3/lib/python3.7/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
```
Using try/except blocks, I'm able to catch this issue and reconnect/resubscribe to the channel, but it still disconnects every 3 minutes. The code which allows reconnection is below

```
import logging
import redis
import time

if __name__ == "__main__":
    log = logging.getLogger(__name__)
    logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(message)s')

    r = redis.Redis(host='127.0.0.1', port=6379, db=0, socket_timeout=None, socket_keepalive=True)
    ps = None

    while True:
        try:
            if ps is None:
                ps = r.pubsub()
                log.info(f"Subcribing to test-channel")
                ps.subscribe("test-channel")

            msg = ps.get_message()
            if msg:
                log.info(f"Pubsub received: {msg}")
            else:
                pass
        except redis.exceptions.ConnectionError as e:
            log.warning(f"Error in redis connection: {e}")
            ps = None

        time.sleep(0.01)
```
And the output from this code can be seen below

```
2020-09-24 13:45:56,829 - Subcribing to test-channel
2020-09-24 13:45:56,844 - Pubsub received: {'type': 'subscribe', 'pattern': None, 'channel': b'test-channel', 'data': 1}
2020-09-24 13:47:09,334 - Error in redis connection: Connection closed by server.
2020-09-24 13:47:09,344 - Subcribing to test-channel
2020-09-24 13:47:09,345 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,356 - Subcribing to test-channel
2020-09-24 13:47:09,356 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,366 - Subcribing to test-channel
2020-09-24 13:47:09,367 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,377 - Subcribing to test-channel
2020-09-24 13:47:09,378 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,388 - Subcribing to test-channel
2020-09-24 13:47:09,389 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,399 - Subcribing to test-channel
2020-09-24 13:47:09,399 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,409 - Subcribing to test-channel
2020-09-24 13:47:09,410 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,420 - Subcribing to test-channel
2020-09-24 13:47:09,420 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,431 - Subcribing to test-channel
2020-09-24 13:47:09,431 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,441 - Subcribing to test-channel
2020-09-24 13:47:09,442 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,452 - Subcribing to test-channel
2020-09-24 13:47:09,453 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,464 - Subcribing to test-channel
2020-09-24 13:47:09,464 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,475 - Subcribing to test-channel
2020-09-24 13:47:09,475 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,486 - Subcribing to test-channel
2020-09-24 13:47:09,486 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,497 - Subcribing to test-channel
2020-09-24 13:47:09,498 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,508 - Subcribing to test-channel
2020-09-24 13:47:09,509 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,519 - Subcribing to test-channel
2020-09-24 13:47:09,520 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,530 - Subcribing to test-channel
2020-09-24 13:47:09,531 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,542 - Subcribing to test-channel
2020-09-24 13:47:09,542 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,553 - Subcribing to test-channel
2020-09-24 13:47:09,553 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,564 - Subcribing to test-channel
2020-09-24 13:47:09,565 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,575 - Subcribing to test-channel
2020-09-24 13:47:09,576 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,586 - Subcribing to test-channel
2020-09-24 13:47:09,587 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,597 - Subcribing to test-channel
2020-09-24 13:47:09,598 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,608 - Subcribing to test-channel
2020-09-24 13:47:09,608 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,618 - Subcribing to test-channel
2020-09-24 13:47:09,619 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:47:09,629 - Subcribing to test-channel
2020-09-24 13:47:09,639 - Pubsub received: {'type': 'subscribe', 'pattern': None, 'channel': b'test-channel', 'data': 1}
2020-09-24 13:50:10,085 - Error in redis connection: Connection closed by server.
2020-09-24 13:50:10,095 - Subcribing to test-channel
2020-09-24 13:50:10,096 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,106 - Subcribing to test-channel
2020-09-24 13:50:10,107 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,117 - Subcribing to test-channel
2020-09-24 13:50:10,118 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,128 - Subcribing to test-channel
2020-09-24 13:50:10,130 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,141 - Subcribing to test-channel
2020-09-24 13:50:10,141 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,151 - Subcribing to test-channel
2020-09-24 13:50:10,152 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,162 - Subcribing to test-channel
2020-09-24 13:50:10,163 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,174 - Subcribing to test-channel
2020-09-24 13:50:10,174 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,184 - Subcribing to test-channel
2020-09-24 13:50:10,184 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,195 - Subcribing to test-channel
2020-09-24 13:50:10,195 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,205 - Subcribing to test-channel
2020-09-24 13:50:10,206 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,216 - Subcribing to test-channel
2020-09-24 13:50:10,217 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,227 - Subcribing to test-channel
2020-09-24 13:50:10,228 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,238 - Subcribing to test-channel
2020-09-24 13:50:10,239 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,249 - Subcribing to test-channel
2020-09-24 13:50:10,250 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,260 - Subcribing to test-channel
2020-09-24 13:50:10,261 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,271 - Subcribing to test-channel
2020-09-24 13:50:10,272 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,283 - Subcribing to test-channel
2020-09-24 13:50:10,283 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,294 - Subcribing to test-channel
2020-09-24 13:50:10,294 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,305 - Subcribing to test-channel
2020-09-24 13:50:10,306 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,316 - Subcribing to test-channel
2020-09-24 13:50:10,317 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,327 - Subcribing to test-channel
2020-09-24 13:50:10,328 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,338 - Subcribing to test-channel
2020-09-24 13:50:10,339 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,349 - Subcribing to test-channel
2020-09-24 13:50:10,350 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,361 - Subcribing to test-channel
2020-09-24 13:50:10,361 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,372 - Subcribing to test-channel
2020-09-24 13:50:10,372 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,382 - Subcribing to test-channel
2020-09-24 13:50:10,382 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,393 - Subcribing to test-channel
2020-09-24 13:50:10,393 - Error in redis connection: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2020-09-24 13:50:10,403 - Subcribing to test-channel
2020-09-24 13:50:10,414 - Pubsub received: {'type': 'subscribe', 'pattern': None, 'channel': b'test-channel', 'data': 1}
```

My understanding is that a redis pubsub client should be able to be kept alive and listening for much longer than the 3 minutes it is able to in its current configuration. This problem also occurs when replacing 
```
msg = ps.get_message()
if msg:
    log.info(f"Pubsub received: {msg}")
```
with
```
for msg in ps.listen():
    log.info(f"Pubsub received: {msg}")
```
So the problem appears (with the same frequency) with ps.get_message() or ps.listen(). Are there any suggestions as to how to keep the pubsub objects alive for longer than this?

**Comment by andymccurdy** [comment]
Try enabling regular health checks via: `r = redis.Redis(..., health_check_interval=60)`

You can read more here: https://github.com/andymccurdy/redis-py#connections

**Comment by nswimmer** [comment]
I've tried a few different options here based on your suggestion and the linked information.

(1) Replacing 
`r = redis.Redis(host='127.0.0.1', port=6379, db=0, socket_timeout=None, socket_keepalive=True)
`
with
`r = redis.Redis(host='127.0.0.1', port=6379, db=0, socket_timeout=None, socket_keepalive=True, health_check_interval=30)
`

(2) Keeping
`r = redis.Redis(host='127.0.0.1', port=6379, db=0, socket_timeout=None, socket_keepalive=True)
`
And calling
` ps.check_health()
`
every 30 seconds

(3) Modifying both the redis client instantiation to use the health_check_interval keyword and explicitly calling `ps.check_health()`

(4) The same as (3), with the addition of calling `ps.ping()` every 10 seconds.

All of these options still exhibit the behavior where the server closes the connection every 3 minutes.

-----

If it's helpful, the config file that's being used has 
`tcp-keepalive 300`
and
`timeout 0`

**Comment by andymccurdy** [comment]
That's odd. It sounds like the connection isn't being dropped due to inactivity then. Specifying `health_check_interval` or regular `pubsub.ping()` calls will produce messages to and from the server.

It looks like you're running the server locally. Is it inside a Docker container? Or are you running any sort of proxy in front of the Redis port?

**Comment by nswimmer** [comment]
To the best of my knowledge, the answer's no to both of those questions.

I updated to use Redis 6.0.8 and Ubuntu 20.04 yesterday since I was seeing this problem with earlier versions of both (Redis 5.0.5 and Ubuntu 19.10) and so both the OS and Redis are 'fresh' installs.

I didn't set up Redis to run inside a Docker container and I've made no configuration changes that would lead me to think there's a proxy in front of the port, unless that's a default setting in Redis/Ubuntu.

**Comment by andymccurdy** [comment]
Could you post the results of the following commands please?

```python
r = redis.Redis()
print(r.config_get())
print(r.info())
```

**Comment by nswimmer** [comment]
Sure thing! 
From `print(r.config_get())`

```
{'rdbchecksum': 'yes',
 'daemonize': 'no',
 'io-threads-do-reads': 'no',
 'lua-replicate-commands': 'yes',
 'always-show-logo': 'yes',
 'protected-mode': 'yes',
 'rdbcompression': 'yes',
 'rdb-del-sync-files': 'no',
 'activerehashing': 'yes',
 'stop-writes-on-bgsave-error': 'yes',
 'dynamic-hz': 'yes',
 'lazyfree-lazy-eviction': 'no',
 'lazyfree-lazy-expire': 'no',
 'lazyfree-lazy-server-del': 'no',
 'lazyfree-lazy-user-del': 'no',
 'repl-disable-tcp-nodelay': 'no',
 'repl-diskless-sync': 'no',
 'gopher-enabled': 'no',
 'aof-rewrite-incremental-fsync': 'yes',
 'no-appendfsync-on-rewrite': 'no',
 'cluster-require-full-coverage': 'yes',
 'rdb-save-incremental-fsync': 'yes',
 'aof-load-truncated': 'yes',
 'aof-use-rdb-preamble': 'yes',
 'cluster-replica-no-failover': 'no',
 'cluster-slave-no-failover': 'no',
 'replica-lazy-flush': 'no',
 'slave-lazy-flush': 'no',
 'replica-serve-stale-data': 'yes',
 'slave-serve-stale-data': 'yes',
 'replica-read-only': 'yes',
 'slave-read-only': 'yes',
 'replica-ignore-maxmemory': 'yes',
 'slave-ignore-maxmemory': 'yes',
 'jemalloc-bg-thread': 'yes',
 'activedefrag': 'no',
 'syslog-enabled': 'no',
 'cluster-enabled': 'no',
 'appendonly': 'no',
 'cluster-allow-reads-when-down': 'no',
 'oom-score-adj': 'no',
 'aclfile': '',
 'unixsocket': '',
 'pidfile': '/var/run/redis_6379.pid',
 'replica-announce-ip': '',
 'slave-announce-ip': '',
 'masteruser': '',
 'masterauth': '',
 'cluster-announce-ip': '',
 'syslog-ident': 'redis',
 'dbfilename': 'dump.rdb',
 'appendfilename': 'appendonly.aof',
 'server_cpulist': '',
 'bio_cpulist': '',
 'aof_rewrite_cpulist': '',
 'bgsave_cpulist': '',
 'supervised': 'no',
 'syslog-facility': 'local0',
 'repl-diskless-load': 'disabled',
 'loglevel': 'notice',
 'maxmemory-policy': 'noeviction',
 'appendfsync': 'everysec',
 'databases': '16',
 'port': '6379',
 'io-threads': '1',
 'auto-aof-rewrite-percentage': '100',
 'cluster-replica-validity-factor': '10',
 'cluster-slave-validity-factor': '10',
 'list-max-ziplist-size': '-2',
 'tcp-keepalive': '300',
 'cluster-migration-barrier': '1',
 'active-defrag-cycle-min': '1',
 'active-defrag-cycle-max': '25',
 'active-defrag-threshold-lower': '10',
 'active-defrag-threshold-upper': '100',
 'lfu-log-factor': '10',
 'lfu-decay-time': '1',
 'replica-priority': '100',
 'slave-priority': '100',
 'repl-diskless-sync-delay': '5',
 'maxmemory-samples': '5',
 'timeout': '0',
 'replica-announce-port': '0',
 'slave-announce-port': '0',
 'tcp-backlog': '511',
 'cluster-announce-bus-port': '0',
 'cluster-announce-port': '0',
 'repl-timeout': '60',
 'repl-ping-replica-period': '10',
 'repl-ping-slave-period': '10',
 'list-compress-depth': '0',
 'rdb-key-save-delay': '0',
 'key-load-delay': '0',
 'active-expire-effort': '1',
 'hz': '10',
 'min-replicas-to-write': '0',
 'min-slaves-to-write': '0',
 'min-replicas-max-lag': '10',
 'min-slaves-max-lag': '10',
 'maxclients': '10000',
 'active-defrag-max-scan-fields': '1000',
 'slowlog-max-len': '128',
 'acllog-max-len': '128',
 'lua-time-limit': '5000',
 'cluster-node-timeout': '15000',
 'slowlog-log-slower-than': '10000',
 'latency-monitor-threshold': '0',
 'proto-max-bulk-len': '536870912',
 'stream-node-max-entries': '100',
 'repl-backlog-size': '1048576',
 'maxmemory': '0',
 'hash-max-ziplist-entries': '512',
 'set-max-intset-entries': '512',
 'zset-max-ziplist-entries': '128',
 'active-defrag-ignore-bytes': '104857600',
 'hash-max-ziplist-value': '64',
 'stream-node-max-bytes': '4096',
 'zset-max-ziplist-value': '64',
 'hll-sparse-max-bytes': '3000',
 'tracking-table-max-keys': '1000000',
 'repl-backlog-ttl': '3600',
 'auto-aof-rewrite-min-size': '67108864',
 'logfile': '',
 'client-query-buffer-limit': '1073741824',
 'watchdog-period': '0',
 'dir': '/',
 'save': '900 1 300 10 60 10000',
 'client-output-buffer-limit': 'normal 0 0 0 slave 268435456 67108864 60 pubsub 33554432 8388608 60',
 'unixsocketperm': '0',
 'slaveof': '',
 'notify-keyspace-events': '',
 'bind': '127.0.0.1',
 'requirepass': '',
 'oom-score-adj-values': '0 200 800'}
```

From `print(r.info())`

```
{'redis_version': '6.0.8',
 'redis_git_sha1': 0,
 'redis_git_dirty': 0,
 'redis_build_id': '92cf5b13814c9963',
 'redis_mode': 'standalone',
 'os': 'Linux 5.3.0-59-generic x86_64',
 'arch_bits': 64,
 'multiplexing_api': 'epoll',
 'atomicvar_api': 'atomic-builtin',
 'gcc_version': '9.2.1',
 'process_id': 8717,
 'run_id': 'f3d72e3bbb9a8438e15db8343762198034e21bbe',
 'tcp_port': 6379,
 'uptime_in_seconds': 158,
 'uptime_in_days': 0,
 'hz': 10,
 'configured_hz': 10,
 'lru_clock': 7155006,
 'executable': '/usr/local/bin/redis-server',
 'config_file': '/etc/redis/redis.conf',
 'io_threads_active': 0,
 'connected_clients': 1,
 'client_recent_max_input_buffer': 2,
 'client_recent_max_output_buffer': 0,
 'blocked_clients': 0,
 'tracking_clients': 0,
 'clients_in_timeout_table': 0,
 'used_memory': 866512,
 'used_memory_human': '846.20K',
 'used_memory_rss': 5668864,
 'used_memory_rss_human': '5.41M',
 'used_memory_peak': 866512,
 'used_memory_peak_human': '846.20K',
 'used_memory_peak_perc': '100.00%',
 'used_memory_overhead': 820026,
 'used_memory_startup': 803040,
 'used_memory_dataset': 46486,
 'used_memory_dataset_perc': '73.24%',
 'allocator_allocated': 1278640,
 'allocator_active': 1572864,
 'allocator_resident': 4386816,
 'total_system_memory': 8210550784,
 'total_system_memory_human': '7.65G',
 'used_memory_lua': 37888,
 'used_memory_lua_human': '37.00K',
 'used_memory_scripts': 0,
 'used_memory_scripts_human': '0B',
 'number_of_cached_scripts': 0,
 'maxmemory': 0,
 'maxmemory_human': '0B',
 'maxmemory_policy': 'noeviction',
 'allocator_frag_ratio': 1.23,
 'allocator_frag_bytes': 294224,
 'allocator_rss_ratio': 2.79,
 'allocator_rss_bytes': 2813952,
 'rss_overhead_ratio': 1.29,
 'rss_overhead_bytes': 1282048,
 'mem_fragmentation_ratio': 6.88,
 'mem_fragmentation_bytes': 4844848,
 'mem_not_counted_for_evict': 0,
 'mem_replication_backlog': 0,
 'mem_clients_slaves': 0,
 'mem_clients_normal': 16986,
 'mem_aof_buffer': 0,
 'mem_allocator': 'jemalloc-5.1.0',
 'active_defrag_running': 0,
 'lazyfree_pending_objects': 0,
 'loading': 0,
 'rdb_changes_since_last_save': 0,
 'rdb_bgsave_in_progress': 0,
 'rdb_last_save_time': 1600990369,
 'rdb_last_bgsave_status': 'ok',
 'rdb_last_bgsave_time_sec': -1,
 'rdb_current_bgsave_time_sec': -1,
 'rdb_last_cow_size': 0,
 'aof_enabled': 0,
 'aof_rewrite_in_progress': 0,
 'aof_rewrite_scheduled': 0,
 'aof_last_rewrite_time_sec': -1,
 'aof_current_rewrite_time_sec': -1,
 'aof_last_bgrewrite_status': 'ok',
 'aof_last_write_status': 'ok',
 'aof_last_cow_size': 0,
 'module_fork_in_progress': 0,
 'module_fork_last_cow_size': 0,
 'total_connections_received': 1,
 'total_commands_processed': 3,
 'instantaneous_ops_per_sec': 0,
 'total_net_input_bytes': 92,
 'total_net_output_bytes': 12808,
 'instantaneous_input_kbps': 0.0,
 'instantaneous_output_kbps': 0.0,
 'rejected_connections': 0,
 'sync_full': 0,
 'sync_partial_ok': 0,
 'sync_partial_err': 0,
 'expired_keys': 0,
 'expired_stale_perc': 0.0,
 'expired_time_cap_reached_count': 0,
 'expire_cycle_cpu_milliseconds': 2,
 'evicted_keys': 0,
 'keyspace_hits': 0,
 'keyspace_misses': 0,
 'pubsub_channels': 0,
 'pubsub_patterns': 0,
 'latest_fork_usec': 0,
 'migrate_cached_sockets': 0,
 'slave_expires_tracked_keys': 0,
 'active_defrag_hits': 0,
 'active_defrag_misses': 0,
 'active_defrag_key_hits': 0,
 'active_defrag_key_misses': 0,
 'tracking_total_keys': 0,
 'tracking_total_items': 0,
 'tracking_total_prefixes': 0,
 'unexpected_error_replies': 0,
 'total_reads_processed': 4,
 'total_writes_processed': 3,
 'io_threaded_reads_processed': 0,
 'io_threaded_writes_processed': 0,
 'role': 'master',
 'connected_slaves': 0,
 'master_replid': '82ffad451fe77dd8edf153d44cf25556fa4d4f70',
 'master_replid2': 0,
 'master_repl_offset': 0,
 'second_repl_offset': -1,
 'repl_backlog_active': 0,
 'repl_backlog_size': 1048576,
 'repl_backlog_first_byte_offset': 0,
 'repl_backlog_histlen': 0,
 'used_cpu_sys': 0.13756,
 'used_cpu_user': 0.175077,
 'used_cpu_sys_children': 0.0,
 'used_cpu_user_children': 0.0,
 'cluster_enabled': 0}
```

**Comment by andymccurdy** [comment]
I don't see anything wrong with your configuration. I'm surprised you're seeing these disconnects, especially when both the client and server are running locally.

It would be interesting to run `redis-cli` locally and use it to subscribe to a channel and see if you're encountering the same 3 minute disconnect times.

**Comment by nswimmer** [comment]
Running locally with `redis-cli` shows the same behavior. It's harder to track the timing exactly, but it kicks me out of the `redis-cli `and back to the standard command line. Without using pubsub, it lets me sit idly and doesn't kick me off.

In addition to that, it kicks me off whether I'm just letting it idle or if I'm actively publishing messages to the channel that the `redis-cli` is listening on.

**Comment by andymccurdy** [comment]
So that suggests that it's something server or OS related rather than a single client. You don't have a `timeout` configured on the Redis server, so I'd be surprised if it was actively disconnecting clients. Unfortunately I don't have much wisdom to offer at this point.

**Comment by nswimmer** [comment]
No problem, thank you for the advice you were able to give and helping me get to the point where at least we figured out that it's OS/server related.
I'll post back here if/when I can figure out a solution to this.

**Comment by nswimmer** [comment]
A bit more development I have noticed with this. I was seeing this problem while I was running the `redis-server` from a systemd redis.service file.

I realized that when I stopped the server from that configuration and ran it from the command line
`sudo redis /path/to/redis.conf`, it ran indefinitely without any trouble.

Have there been any problems seen in running the redis server via a systemd unit file?

**Comment by nswimmer** [comment]
I think I've found the fix! When running it 'in the background' from a redis.service systemd file, it needs the keywords `daemonize` and `supervision` changed from their defaults.

Switching 'daemonize' from `no` to `yes` and `supervision` from `none1 to `systemd` fixed this problem!
