### ISSUE TITLE
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

### ISSUE THREAD

**Issue by LeopoldACC** [andymccurdy/redis-py#1474]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on? 3.5.3

**Platform**: What platform / version?  Python 3.8 on Ubuntu 20.04 

**Description**: Description of your issue, stack traces from errors and code that reproduces the issue

hello,I just installed redis in python, but when I use the redis to fetch my data in localhost as 127.0.0.1,show connection refused error as you,can you help me?Thanks!
```python
Traceback (most recent call last):
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gz/.vscode/extensions/ms-python.python-2021.3.680753044/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/gz/.vscode/extensions/ms-python.python-2021.3.680753044/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/gz/.vscode/extensions/ms-python.python-2021.3.680753044/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/pcdseg.py", line 242, in <module>
    evaluate(args)
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/pcdseg.py", line 229, in evaluate
    acc, miou = test_kitti_semseg(model.eval(), testdataloader,args.model_name,num_classes,class_names)
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/pcdseg.py", line 64, in test_kitti_semseg
    for points, target in tqdm(loader, total=len(loader), smoothing=0.9, dynamic_ncols=True):
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/data_utils/SemKITTI_Loader.py", line 92, in __getitem__
    point_cloud, label = self.get_data(self.keys[index])
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/data_utils/SemKITTI_Loader.py", line 77, in get_data
    if not self.np_redis.exists(key):
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/data_utils/redis_utils.py", line 49, in exists
    return bool(self.handle.execute_command('EXISTS ' + key))
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
```
as I run the code as below to set and get,it also connection refused
```python
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> r = redis.Redis(host='127.0.0.1', port=6379,db=0)
>>> r.set('a','m')
Traceback (most recent call last):
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
```
should I install the redis in apt-get?Thks a lot!

**Comment by LeopoldACC** [comment]
I found the [https://pypi.org/project/redis/](https://pypi.org/project/redis/) show the information below.
```shell
Installation
redis-py requires a running Redis server. See Redis’s quickstart for installation instructions.
```
I found reason is that I didn't install the redis lol.If anyone condition like me,can follow the pipeline of [install tutorial](https://redis.io/topics/quickstart) to make file first and start redis-server firstly.

**Comment by New-dev0** [comment]
I am getting Redis Connection Error, while using cloud host, what can i do for it ? It occurs much frequently for me....

**Comment by liavst2** [comment]
> I am getting Redis Connection Error, while using cloud host, what can i do for it ? It occurs much frequently for me....

+1 here.

**Comment by SwapnilH09** [comment]
I am facing a similar issue. I was just playing around with redis-enterprise cloud. Although, when I created an redis instance using another account, it ran smoothly

**Comment by natanzi** [comment]
Is there any update for this issue?

**Comment by LookInFuture** [comment]
Any update on this error? Constantly facing this and no exact solutions on handling it. 

p.s. Redis is starting in Docker container.

**Comment by giantvision** [comment]
1. To start the Redis server run:

    ```shell
    import redis_server
    !$redis_server.REDIS_SERVER_PATH --daemonize yes
    ```

> NOTE:
>
> Alternately you can start the Redis server without shell commands, using a Python subprocess:
>
> ```python
> import subprocess
> import redis_server
> subprocess.Popen([redis_server.REDIS_SERVER_PATH])
> ```
