### ISSUE TITLE
'long' object has no attribute 'encode'

### ISSUE THREAD

**Issue by zerogtw** [andymccurdy/redis-py#1480]
**Version**: 2.10.3

**Platform**: Python 2.7.5 on  Ubuntu 16.04 

**Description**: When trying to use pipeline with command that reply with integer value, exception raise.

## Example

```python3
r_old_master = redis.StrictRedis(host=old_master_host, port=old_master_port)
p_old_master = r_old_master.pipeline(transaction=True)
p_old_master.execute_command('CLIENT KILL', 'TYPE', 'normal')
p_old_master.execute_command('CLIENT KILL', 'TYPE', 'pubsub')
p_old_master.execute_command("SET", "my_key", “my_value”)
p_old_master.execute()
```

As `CLIENT KILL TYPE <type>` will return **the number of clients killed.**, 

```python3
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 2501, in _execute_transaction
    r = self.response_callbacks[command_name](r, **options)
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 238, in bool_ok
    return nativestr(response) == 'OK'
  File "build/bdist.linux-x86_64/egg/redis/_compat.py", line 19, in <lambda>
    x if isinstance(x, str) else x.encode('utf-8', 'replace')
AttributeError: 'long' object has no attribute 'encode'
```

I find the source code is like that, if x is str i think exception will be raise

```python3
    def nativestr(x):
        return x if isinstance(x, str) else x.encode('utf-8', 'replace')
```

## my test

```python3
>>> def foo(x):
...     return x if isinstance(x, str) else x.encode('utf-8', 'replace')
... 
>>> a = 3L
>>> type(a)
<type 'long'>
>>> foo(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in foo
AttributeError: 'long' object has no attribute 'encode'
```

**Comment by zerogtw** [comment]
I think the reason is that  old version redis-py can not adapt to the command ('CLIENT KILL', *args)  because not noly the pipeline but the StrictRedis client i saw the same error.

It is fine if i try to use the whole command like:

```python
r_old_master.execute_command('CLIENT KILL TYPE pubsub')
p_old_master.execute_command('CLIENT KILL TYPE pubsub')
```
