### ISSUE TITLE
Mishandles encodings that are not a superset of ascii

### ISSUE THREAD

**Issue by p** [andymccurdy/redis-py#430]
redis-py 2.9.1:

<pre>
>>> import redis
>>> c=redis.Redis(charset='utf-16')
>>> c.set('hello','world')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sandbox/33/lib/python3.3/site-packages/redis/client.py", line 897, in set
    return self.execute_command('SET', *pieces)
  File "/home/sandbox/33/lib/python3.3/site-packages/redis/client.py", line 461, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/sandbox/33/lib/python3.3/site-packages/redis/client.py", line 471, in parse_response
    response = connection.read_response()
  File "/home/sandbox/33/lib/python3.3/site-packages/redis/connection.py", line 344, in read_response
    raise response
redis.exceptions.ResponseError: unknown command '\ufffd\ufffdS'
</pre>

It looks like redis encodes command itself using the configured encoding, but encoding should only apply to user data (keys/values).

**Comment by p** [comment]
@andymccurdy the fix works, thank you!
