### ISSUE TITLE
`from_url` doesn't convert `socket_timeout` to float

### ISSUE THREAD

**Issue by lilydjwg** [andymccurdy/redis-py#539]
``` pytb
>>> import redis
>>> r = redis.StrictRedis.from_url('redis://?socket_timeout=1')
>>> r.get('xxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/redis/client.py", line 863, in get
    return self.execute_command('GET', name)
  File "/usr/lib/python3.4/site-packages/redis/client.py", line 564, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python3.4/site-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python3.4/site-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/usr/lib/python3.4/site-packages/redis/connection.py", line 433, in connect
    sock = self._connect()
  File "/usr/lib/python3.4/site-packages/redis/connection.py", line 473, in _connect
    sock.settimeout(self.socket_connect_timeout)
TypeError: a float is required
```

**Comment by gyermolenko** [comment]
hi @lilydjwg 
The issue was probably resolved at some point. Could you please recheck?

For `redis 3.2.1`:
```python3
>>> import redis
>>> r = redis.StrictRedis.from_url('redis://?socket_timeout=1')
>>> r.get('xxx')
# no exception
>>> r.connection_pool.connection_kwargs
{'socket_timeout': 1.0, 'host': None, 'port': 6379, 'password': None, 'db': 0}
```

**Comment by lilydjwg** [comment]
It has been a lot of time since the error happened and I don't have redis at hand. Let's assume it's fixed.
