### ISSUE TITLE
Ubuntu 14: ImportError during install

### ISSUE THREAD

**Issue by vigoatrook** [andymccurdy/redis-py#581]
Hi there, I've been trying to install redis but kept getting the same error with different install methods. Below is the description of my problem. Please let me know if more details are needed.

OS: Ubuntu 14.04
Python version: 2.7.6
pip version: 1.5.4 (also tried 6.0.6)

Problem: failed installing through pip install redis, also tried with python setup.py install from source. no luck :(

Error message given by pip:
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/redis
Storing debug log for failure in /root/.pip/pip.log

Error message given by python:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip_build_root/redis/setup.py", line 41, in <module>
    'Programming Language :: Python :: 3.3',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "<string>", line 12, in replacement_run
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named version

**Comment by vigoatrook** [comment]
Update: 

Found a solution when I was hanging out at Beaver's repo, someone suggested the following solution that worked for me:

`pip uninstall python-daemon`
`pip install python-daemon==1.6.1`
then: 
`pip install beaver==33`

Link: https://github.com/josegonzalez/python-beaver/issues/286#issuecomment-70307895
