### ISSUE TITLE
bug with concurrent.futures.ProcessPoolExecutor

### ISSUE THREAD

**Issue by huskyii** [andymccurdy/redis-py#606]
I got following traceback information

``` python
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/queues.py", line 242, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class '_thread.lock'>: attribute lookup lock on _thread failed
```

when I trying run some code like

``` python
from concurrent.futures import ProcessPoolExecutor

redis_pool = ConnectionPool()
redis_list = [redis_pool for _ in range(10)]
with ProcessPoolExecutor(8) as executor:
    executor.map(some_func, redis_list)
```

package information:
hiredis (0.1.6)
redis (2.10.3)
Python3.4.3

**Comment by leokhachatorians** [comment]
I ran into a similar issue myself. Ended up just not using a pool (shrug)

**Comment by mattip** [comment]
This is on macOS, right? I think this is because the Pool uses spawn on macOS rather than fork, so it has to pickle everything.

**Comment by huskyii** [comment]
> This is on macOS, right? I think this is because the Pool uses spawn on macOS rather than fork, so it has to pickle everything.

Yes, macOS
