### ISSUE TITLE
Connect via Unix Socket and Connection Pool

### ISSUE THREAD

**Issue by cgloeckner** [andymccurdy/redis-py#624]
Hi, I'm not actual sure whether this should work (in theory) or not (maybe a misconception on my side?). I configured my redis server to allow connections via the unix domain socket. Unfortunately my testing code (using a connection pool) is not working that way. Could it be my fault based on a wrong usage? Using the unix domain socket without connection pool is working great.

```python
Python 3.4.0 (default, Apr 11 2014, 13:05:18) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> rdb = redis.ConnectionPool(unix_socket_path="/tmp/redis.sock")
>>> r = redis.Redis(connection_pool=rdb)
>>> r.info()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 872, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 657, in info
    return self.execute_command('INFO')
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 562, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 874, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 883, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'unix_socket_path'
```

redis-py was installed using pip. Any suggestions?

**Comment by andymccurdy** [comment]
You need to specify the `connection_class` argument when not using the normal `Connection` class.

```python
>>> import redis
>>> rdb = redis.ConnectionPool(connection_class=UnixDomainSocketConnection, unix_socket_path="/tmp/redis.sock")
>>> r = redis.Redis(connection_pool=rdb)
```

**Comment by cgloeckner** [comment]
Ah thanks. :)

**Comment by cgloeckner** [comment]
Thanks, but unfortunately this isn't working, too:

```python
>>> import redis
>>> rdb = redis.ConnectionPool(connection_class=redis.UnixDomainSocketConnection, unix_socket_path="/tmp/redis.sock")
>>> r = redis.Redis(connection_pool=rdb)
>>> r.info()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 872, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 657, in info
    return self.execute_command('INFO')
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 562, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 874, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 883, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'unix_socket_path'
```

**Comment by andymccurdy** [comment]
Sorry, the argument names are slightly different between the client class and the the connection. The following code works for me:

```python
import redis
rdb = redis.ConnectionPool(connection_class=redis.UnixDomainSocketConnection, path="/tmp/redis.sock")
r = redis.Redis(connection_pool=rdb)
```

While the client class itself accepts `unix_socket_path` and chooses the `UnixDomainSocketConnection` class as a convenience, I prefer to keep the `ConnectionPool` completely separate from `Connection` subclasses.

**Comment by cgloeckner** [comment]
Thanks, again! This time it's running :)
