### ISSUE TITLE
LREM through ConnectionPool

### ISSUE THREAD

**Issue by tophsic** [andymccurdy/redis-py#678]
Using [Will bot](https://github.com/skoczen/will) which use redis 2.10.3, I found a bug on `redis.Redis.lrem` method. Tried on 2.10.3 and 2.10.5 with python 2.7.

```bash
>>> import redis
>>> pool = redis.ConnectionPool(host='localhost', port=6379, db=0) 
>>> r = redis.Redis(connection_pool=pool)
>>> r.lpush('list', 'myValue')
1L
>>> r.lrem('list', 0, 'myValue')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "HOME/.virtualenvs/redis/lib/python2.7/site-packages/redis/client.py", line 2026, in lrem
    return self.execute_command('LREM', name, num, value)
  File "HOME/.virtualenvs/redis/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "HOME/.virtualenvs/redis/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "HOME/.virtualenvs/redis/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: value is not an integer or out of range
```

I do not have such exception when I directly instantiate `Redis` without `ConnectionPool`.

**Comment by andymccurdy** [comment]
`LREM` differs between the `Redis` and `StrictRedis` classes. You want to be using the `StrictRedis` class.

**Comment by tophsic** [comment]
Unfortunately, I would like just to extend Will bot storage stack which use `Redis` :disappointed: and not StrictRedis.

**Comment by andymccurdy** [comment]
Then just switch the order of the last two args.

**Comment by tophsic** [comment]
Thx :+1:
