### ISSUE TITLE
Connection Refused by Machine

### ISSUE THREAD

**Issue by aewhatley** [andymccurdy/redis-py#690]
I am trying to run the commands in the README in command prompt, and I got a long error message after trying:

import redis
r = redis.StrictRedis(host='localhost', port=6379, db=0)
r.set('foo', 'bar')

The error message is:

Traceback (most recent call last):
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 439, in connect
    sock = self._connect()
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 494, in _connect
    raise err
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\client.py", line 572, in execute_command
    connection.send_command(*args)
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 538, in send_packed_command
    self.connect()
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 439, in connect
    sock = self._connect()
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 494, in _connect
    raise err
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\client.py", line 1072, in set
    return self.execute_command('SET', *pieces)
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\client.py", line 578, in execute_command
    connection.send_command(*args)
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 538, in send_packed_command
    self.connect()
  File "C:\Users\Alexander\Anaconda3\lib\site-packages\redis\connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.

I have no firewall installed, or anything else I can think of that can possibly be blocking the connection. I am running Python 3.5 (Anaconda). Thanks for your help.

**Comment by andymccurdy** [comment]
Where is your Redis server running?

**Comment by kute** [comment]
same issue to me and my redis is running on windows, because of firewall ？

**Comment by chancyk** [comment]
I am still having this issue as well. In my case, it's [socket.getaddrinfo](https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L511) is resolving to the IPv6 loopback (::1) and then the IPv4 loopback (127.0.0.1) for localhost. ::1 fails with ConnectionRefused after 1 second timeout, but is silently discarded with no warning, and then the 127.0.0.1 connections.

I'm not sure why ::1 is failing in the first place, but maybe a warning should at least be raised on connection failure? This took me at least an hour to discover and was introducing a 1 second latency into every command I would execute due to default `connect` timeout.

**Comment by Pradeep119** [comment]
you have download and run redis server. 
use this link  :   https://github.com/rgl/redis/downloads

**Comment by Grokzen** [comment]
@andymccurdy This could be considered not a redis-py issue, but more a operational issue of redis itself. No need to keep this open any longer as it do not mention any real issue with the client code, but how the redis itself is operated.
