### ISSUE TITLE
pubsub.run_in_thread throws exceptions in case of lost redis connection

### ISSUE THREAD

**Issue by baranyaib90** [andymccurdy/redis-py#717]
I started the thread for keyspace events:

```
self._pubsub = self._redis.pubsub()
self._pubsub.psubscribe(**{'__keyspace@0__:*': self._redis_notification})
self._pubsub_thread = self._pubsub.run_in_thread(sleep_time=0.5)
```

If the connection broke with redis (redis process stopped), lot of exceptions appeared.
And I do not know, how my main thread could handle this (or get notified about it).

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 129, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 2165, in _execute
    return command(*args)
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 494, in _connect
    raise err
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 2345, in run
    timeout=sleep_time)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 2260, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 2183, in parse_response
    return self._execute(connection, connection.read_response)
  File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 2172, in _execute
    connection.connect()
  File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 172.18.0.4:6379. Connection refused.

```

**Comment by wiwat-tharateeraparb** [comment]
+1

**Comment by wiwat-tharateeraparb** [comment]
It will be good if we can register a callback or handler for run_in_thread's exception.

**Comment by wiwat-tharateeraparb** [comment]
I have worked around this by polling the pubsub thread's health e.g. `self._pubsub_thread.is_alive()` and stop the thread when it's not alive anymore. But it will be good if we can register a callback or handler for run_in_thread's exception.

**Comment by AlexEshoo** [comment]
I also have this issue. The `run_in_thread` method should definitely be able to do some error handling to ride through connection losses. I'd like to avoid re-implementing the thread object just to include a try except block in my application to do this.

**Comment by dmarsh19** [comment]
I am having similar issues. Its additionally problematic because `ConnectionError` exceptions bubble up all the way from `SocketBuffer` to `PubSubWorkerThread.run()` without being handled, which eventually kills the thread unnoticed. `threading.excepthook()` can be used in Python3.8 to catch exceptions as a workaround.

**Comment by baranyaib90** [comment]
I would say, that `exception_handler` argument of `run_in_thread` gives possibility to detect and log problems. Thanks to #1395
Also - delayed - thread restart could be implemented there.
So I'm closing the ticket.
