### ISSUE TITLE
redis-py huge latency

### ISSUE THREAD

**Issue by mullakhmetov** [andymccurdy/redis-py#740]
I got some problems on one production server. Redis-py opening connection for so long time.
```
>>>import cProfile
>>>import redis
>>>r = redis.Redis()
>>>cProfile.run("r.set('foo', 'bar')")
23    0.000    0.000    0.000    0.000 {len}
    1    0.000    0.000    0.000    0.000 connection.py:112(_read_from_socket)
    1    0.000    0.000    0.000    0.000 connection.py:156(readline)
    1    0.000    0.000    0.000    0.000 connection.py:175(purge)
    1    0.000    0.000    0.000    0.000 connection.py:192(__init__)
    1    0.000    0.000    0.000    0.000 connection.py:203(on_connect)
    1    0.000    0.000    0.000    0.000 connection.py:223(read_response)
    1    0.000    0.000    0.000    0.000 connection.py:385(__init__)
    1    0.000    0.000  127.266  127.266 connection.py:428(connect)
    1    0.000    0.000  127.266  127.266 connection.py:451(_connect)
    1    0.000    0.000    0.000    0.000 connection.py:501(on_connect)
    1    0.000    0.000  127.266  127.266 connection.py:529(send_packed_command)
    1    0.000    0.000  127.266  127.266 connection.py:554(send_command)
    1    0.000    0.000    0.000    0.000 connection.py:566(read_response)
    3    0.000    0.000    0.000    0.000 connection.py:577(encode)
    1    0.000    0.000    0.000    0.000 connection.py:593(pack_command)
    1    0.000    0.000    0.000    0.000 connection.py:68(__init__)
    2    0.000    0.000    0.000    0.000 connection.py:858(_checkpid)
    1    0.000    0.000    0.000    0.000 connection.py:868(get_connection)
    1    0.000    0.000    0.000    0.000 connection.py:878(make_connection)
    1    0.000    0.000    0.000    0.000 connection.py:885(release)
    1    0.000    0.000    0.000    0.000 connection.py:99(__init__)
    2    0.000    0.000    0.000    0.000 socket.py:185(__init__)
    1    0.000    0.000    0.000    0.000 socket.py:192(close)
    8    0.000    0.000  127.264   15.908 socket.py:223(meth)
    1    0.001    0.001    0.001    0.001 {_socket.getaddrinfo}
    1    0.000    0.000    0.000    0.000 {cStringIO.StringIO}
   20    0.000    0.000    0.000    0.000 {getattr}
   11    0.000    0.000    0.000    0.000 {isinstance}
   13    0.000    0.000    0.000    0.000 {len}
    1    0.000    0.000    0.000    0.000 {method 'add' of 'set' objects}
    2    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
    2  127.264   63.632  127.264   63.632 {method 'connect' of '_socket.socket' objects}
    1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
    2    0.000    0.000    0.000    0.000 {method 'endswith' of 'str' objects}
    4    0.000    0.000    0.000    0.000 {method 'join' of 'str' objects}
    1    0.000    0.000    0.000    0.000 {method 'pop' of 'list' objects}
    2    0.000    0.000    0.000    0.000 {method 'readline' of 'cStringIO.StringO' objects}
    1    0.000    0.000    0.000    0.000 {method 'recv' of '_socket.socket' objects}
    1    0.000    0.000    0.000    0.000 {method 'remove' of 'set' objects}
    4    0.000    0.000    0.000    0.000 {method 'seek' of 'cStringIO.StringO' objects}
    1    0.000    0.000    0.000    0.000 {method 'sendall' of '_socket.socket' objects}
    2    0.000    0.000    0.000    0.000 {method 'setsockopt' of '_socket.socket' objects}
    3    0.000    0.000    0.000    0.000 {method 'settimeout' of '_socket.socket' objects}
    1    0.000    0.000    0.000    0.000 {method 'truncate' of 'cStringIO.StringO' objects}
    1    0.000    0.000    0.000    0.000 {method 'write' of 'cStringIO.StringO' objects}
    3    0.000    0.000    0.000    0.000 {posix.getpid}
   18    0.000    0.000    0.000    0.000 {setattr}

```
**System:**
- Linux 3.16.0-36-generic Ubuntu 14.04

- Python 2.7.6

- redis-py 2.10.3

- Redis 2.8.19

I'm sure it's not redis or connection problems (redis runs locally)

```
redis-benchmark -t set -n 10000 q
===== q ======
  10000 requests completed in 0.17 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.01% <= 1 milliseconds
99.11% <= 2 milliseconds
99.51% <= 15 milliseconds
100.00% <= 15 milliseconds
57471.27 requests per second
```

**Comment by andymccurdy** [comment]
Does the same code work on other servers in your production environment? What's different about this one?

You could try using the `socket_connect_timeout` setting which will raise an exception after N seconds of being unable to connect. The exception message might provide you more insight into what's happening.

```redis.Redis(socket_connect_timeout=5)```

**Comment by mullakhmetov** [comment]
Code works fine on ~30 another servers. I can't say what's the different between them, each serviced by client.

```
>>> import redis
>>> import cProfile
>>> r = redis.Redis(socket_connect_timeout=5)
>>> cProfile.run("r.set('foo', 'bar')")
       143 function calls in 5.007 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    5.007    5.007 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 _compat.py:18(<lambda>)
        5    0.000    0.000    0.000    0.000 _compat.py:21(<lambda>)
        1    0.000    0.000    0.000    0.000 _compat.py:23(<lambda>)
        1    0.000    0.000    5.007    5.007 client.py:1024(set)
        1    0.000    0.000    0.000    0.000 client.py:355(<lambda>)
        1    0.000    0.000    5.007    5.007 client.py:558(execute_command)
        1    0.000    0.000    0.000    0.000 client.py:575(parse_response)
        1    0.000    0.000    0.000    0.000 connection.py:112(_read_from_socket)
        1    0.000    0.000    0.000    0.000 connection.py:156(readline)
        1    0.000    0.000    0.000    0.000 connection.py:175(purge)
        1    0.000    0.000    0.000    0.000 connection.py:192(__init__)
        1    0.000    0.000    0.000    0.000 connection.py:203(on_connect)
        1    0.000    0.000    0.000    0.000 connection.py:223(read_response)
        1    0.000    0.000    0.000    0.000 connection.py:385(__init__)
        1    0.000    0.000    5.007    5.007 connection.py:428(connect)
        1    0.000    0.000    5.006    5.006 connection.py:451(_connect)
        1    0.000    0.000    0.000    0.000 connection.py:501(on_connect)
        1    0.000    0.000    5.007    5.007 connection.py:529(send_packed_command)
        1    0.000    0.000    5.007    5.007 connection.py:554(send_command)
        1    0.000    0.000    0.000    0.000 connection.py:566(read_response)
        3    0.000    0.000    0.000    0.000 connection.py:577(encode)
        1    0.000    0.000    0.000    0.000 connection.py:593(pack_command)
        1    0.000    0.000    0.000    0.000 connection.py:68(__init__)
        2    0.000    0.000    0.000    0.000 connection.py:858(_checkpid)
        1    0.000    0.000    0.000    0.000 connection.py:868(get_connection)
        1    0.000    0.000    0.000    0.000 connection.py:878(make_connection)
        1    0.000    0.000    0.000    0.000 connection.py:885(release)
        1    0.000    0.000    0.000    0.000 connection.py:99(__init__)
        2    0.000    0.000    0.000    0.000 socket.py:185(__init__)
        1    0.000    0.000    0.000    0.000 socket.py:192(close)
        8    0.000    0.000    5.006    0.626 socket.py:223(meth)
        1    0.001    0.001    0.001    0.001 {_socket.getaddrinfo}
        1    0.000    0.000    0.000    0.000 {cStringIO.StringIO}
       20    0.000    0.000    0.000    0.000 {getattr}
       11    0.000    0.000    0.000    0.000 {isinstance}
       13    0.000    0.000    0.000    0.000 {len}
        1    0.000    0.000    0.000    0.000 {method 'add' of 'set' objects}
        2    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
        2    5.005    2.503    5.005    2.503 {method 'connect' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        2    0.000    0.000    0.000    0.000 {method 'endswith' of 'str' objects}
        4    0.000    0.000    0.000    0.000 {method 'join' of 'str' objects}
        1    0.000    0.000    0.000    0.000 {method 'pop' of 'list' objects}
        2    0.000    0.000    0.000    0.000 {method 'readline' of 'cStringIO.StringO' objects}
        1    0.000    0.000    0.000    0.000 {method 'recv' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {method 'remove' of 'set' objects}
        4    0.000    0.000    0.000    0.000 {method 'seek' of 'cStringIO.StringO' objects}
        1    0.000    0.000    0.000    0.000 {method 'sendall' of '_socket.socket' objects}
        2    0.000    0.000    0.000    0.000 {method 'setsockopt' of '_socket.socket' objects}
        3    0.000    0.000    0.000    0.000 {method 'settimeout' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {method 'truncate' of 'cStringIO.StringO' objects}
        1    0.000    0.000    0.000    0.000 {method 'write' of 'cStringIO.StringO' objects}
        3    0.000    0.000    0.000    0.000 {posix.getpid}
       18    0.000    0.000    0.000    0.000 {setattr}
```
With passed socket_connect_timeout connection opening duration ~ timeout. No exceptions were raised, `r.set('foo', 'bar')` returned True.

**Comment by andymccurdy** [comment]
Are you use `SET` returned `True`? The profile shows that `Connection.connect` took 5 seconds to return, which suggests that a `TimeoutError` was raised based on the `socket_connect_timeout` value.

I'd try against without running the profile. Just run manually:

```
import redis
r = redis.Redis(socket_connect_timeout=5)
r.set('foo', 'bar')
```

And see what happens. If it raises a `TimeoutError`, no connection could be established within 5 seconds. There could be many reasons why this would happen. Several of which: a) /etc/hosts overrides "localhost", the redis process isn't stable (perhaps the redis `INFO` command could tell us more -- it provides an uptime value), something weird is happening with networking, either at the OS or the Python level. 

If it raises something else, that's more information to debug with.

If the set command works, then I'm not sure why it wouldn't work in your application running on the same server.

**Comment by mullakhmetov** [comment]
```
>>> import redis
>>> r = redis.Redis(socket_connect_timeout=5)
>>> r.set('foo', 'bar')
True
```
Sorry, I mean that in the last sentence.

**Comment by andymccurdy** [comment]
Then it's quite hard to tell what's wrong...

**Comment by mullakhmetov** [comment]
I got some details:
```
>>>socket.getaddrinfo('localhost', 6379)
[(10, 1, 6, '', ('::1', 6379, 0, 0)), (10, 2, 17, '', ('::1', 6379, 0, 0)), (10, 3, 0, '', ('::1', 6379, 0, 0)), (2, 1, 6, '', ('127.0.0.1', 6379)), (2, 2, 17, '', ('127.0.0.1', 6379)), (2, 3, 0, '', ('127.0.0.1', 6379))]
```
Socket created with parameters only in 1st tuple raises `TimeoutError`

```
>>> sock_info = socket.getaddrinfo('localhost', 6379)
>>> sock = socket.socket(*sock_info[0][:3])
>>> sock.connect(('localhost', 6379))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out
```
After socket.error was caught comes next iteration and connection established successfully.

**Comment by andymccurdy** [comment]
Maybe an IPv6 issue? Perhaps it's trying to connection on IPv6 first and then falling back to IPv4 on failure. Perhaps the Redis server isn't listening on IPv6?

**Comment by mullakhmetov** [comment]
But `sock = socket.socket(10, 2, 17); sock.connect('localhost', 6379)` connected successfully. First argument 10 means IPV6 connection, isn't it?

**Comment by andymccurdy** [comment]
Off the top of my head I'm not sure. On OSX, IPv6 is `30`.

```
In [2]: socket.getaddrinfo('localhost', 6379)
Out[2]: 
[(30, 2, 17, '', ('::1', 6379, 0, 0)),
 (30, 1, 6, '', ('::1', 6379, 0, 0)),
 (2, 2, 17, '', ('127.0.0.1', 6379)),
 (2, 1, 6, '', ('127.0.0.1', 6379)),
 (30, 2, 17, '', ('fe80::1%lo0', 6379, 0, 1)),
 (30, 1, 6, '', ('fe80::1%lo0', 6379, 0, 1))]
```

**Comment by mullakhmetov** [comment]
On production environment IPv6 is 10, I'm sure.
```
socket.AF_INET6
10
socket.AF_INET
2
socket.SOCK_STREAM
1
socket.SOCK_DGRAM
2
socket.IPPROTO_TCP
6
socket.IPPROTO_UDP
17
```
So redis don't accept ipv6/stream/tcp connections, but ipv6/datagram/udp do.

**Comment by mullakhmetov** [comment]
Well, my problem is out of topic, so it can be closed I guess.

**Comment by andymccurdy** [comment]
closing for now. if you figure out that there's an issue with redis-py, please re-open the issue.
