### ISSUE TITLE
TimeoutError using BRPOP on a Sentinel-derived Redis object

### ISSUE THREAD

**Issue by kblin** [andymccurdy/redis-py#748]
I seem to be getting a TimeoutError when trying to use Redis.brpop() with a timeout value specified when the Redis object comes from a sentinel.master_for() call.
I'm unable to find any mention of this in the documentation, so I was wondering how to use blocking operations with a Redis Sentinel setup.

**Comment by andymccurdy** [comment]
What version of redis-py? Can you provide a traceback?

If you're specifying a `socket_timeout` value that's less than the timeout you're supplying to `BRPOP`, you'd certainly get a `TimeoutError`.

**Comment by kblin** [comment]
redis-py 2.10.5

Traceback for a BRPOPLPUSH example is
```
  File "./runSMASH", line 148, in run
    uid = redis_store.brpoplpush('jobs:queued', '%s:queued' % options.name, 5)
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/client.py", line 1196, in brpoplpush
    return self.execute_command('BRPOPLPUSH', src, dst, timeout)
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/sentinel.py", line 55, in read_response
    return super(SentinelManagedConnection, self).read_response()
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/connection.py", line 353, in read_response
    raise TimeoutError("Timeout reading from socket")
redis.exceptions.TimeoutError: Timeout reading from socket
```
where redis_store was set up by the following code:
```
def get_storage(host, port, timeout):
    sentinel = Sentinel([(host, port)], socket_timeout=timeout)
    redis_store = sentinel.master_for(service, redis_class=redis.Redis, socket_timeout=timeout)
    return redis-store
```
With a `timeout` value of `6`, while the `brpoplpush()` call had a timeout of `5`. From adding some more logging output to this, it looks like this only happens on the second time I call `brpoplpush`.

**Comment by kblin** [comment]
I've attached a minimal reproducer using BRPOP (with txt ending as GitHub doesn't allow .py uploads).
[minimal.txt](https://github.com/andymccurdy/redis-py/files/308621/minimal.txt)

Logging output and backtrace is as follows:

```
$ ./minimal.txt 5
2016-06-10 10:26:28,116 DEBUG: Setting up redis connection with timeout 6
2016-06-10 10:26:28,116 DEBUG: calling BRPOP with timeout 5
2016-06-10 10:26:34,048 DEBUG: BRPOP returned None
2016-06-10 10:26:34,048 DEBUG: calling BRPOP with timeout 5
Traceback (most recent call last):
  File "./minimal.txt", line 27, in <module>
    main()
  File "./minimal.txt", line 22, in main
    ret = redis_store.brpop('empty_list', timeout)
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/client.py", line 1183, in brpop
    return self.execute_command('BRPOP', *keys)
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/sentinel.py", line 55, in read_response
    return super(SentinelManagedConnection, self).read_response()
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/home/kai/.virtualenvs/runsmash/local/lib/python2.7/site-packages/redis/connection.py", line 353, in read_response
    raise TimeoutError("Timeout reading from socket")
redis.exceptions.TimeoutError: Timeout reading from socket
```

**Comment by andymccurdy** [comment]
Thanks for sharing. This isn't a Sentinel issue. I was able to reproduce with a single connection directly to an older Redis instance.

Digging a little deeper, I found that blocking operations in older versions of the Redis server seem to block for ~1 second longer than the timeout value specified in the command. Here's a quick test against Redis server version 2.8.9:

```python
import redis
import time
r = redis.Redis()
while True:
    start = time.time()
    r.brpop('empty_list', 2)
    print(time.time() - start)

========================================

2.31329989433
2.98670887947
3.02368402481
2.92817497253
3.0240240097
2.95754408836
3.08876609802
2.93315005302
3.05143404007
2.96656012535
3.0230691433
3.02029109001
2.92922782898
3.04303789139
3.02264690399
2.93132710457
3.02591609955
3.02673983574
3.03458189964
2.92833304405
3.0344619751
3.02393507957
2.93883299828
3.02359700203
3.02560591698
2.94614887238
3.04940986633
3.02766919136
2.93267679214
3.02543306351
3.01413702965
2.9295129776
3.03954100609
3.04726982117
2.9274289608
3.04883909225
2.93907094002
3.06049489975
3.02760791779
2.9365170002
3.05960202217
2.91789102554
3.030189991
3.0652449131
2.94838213921
2.96563601494
3.02874207497
3.04442596436
2.97513604164
3.03070402145
2.95086503029
3.02796816826
2.93137097359
3.02688598633
3.05013203621
2.94903802872
3.05855798721
2.92771196365
```

Even though I only specified to block for 2 seconds, Redis almost always waits until around 2.9-3.1 seconds to actually send a `None` value back. I also tested against Redis server version 3.2.0 and the timeouts seem much closer to the specified value, generally only 100-200ms greater than the specified value.

Based on this, I'd suggest specifying your `socket_timeout` value to be at least 2 full seconds more than the timeout value you're passing to `BRPOP`. After I adjusted the value of `socket_timeout` to 7, I never saw the `TimeoutError` with a 5 second timeout to `BRPOP`.

**Comment by kblin** [comment]
Ok, curious. Thanks for the workaround. :)
