### ISSUE TITLE
Unable to install on Ubuntu Xenial (16.04) with pip- 8.1.1

### ISSUE THREAD

**Issue by TanmayaA** [andymccurdy/redis-py#761]
Seeing this error when I try to install this package using system default pip (8.1.1) on Ubuntu Xenial (16.04):
```
Collecting redis (from -r requirements/main.txt (line 2))
  Using cached redis-2.10.5-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
```

**Comment by TanmayaA** [comment]
Spoke too soon. Sorry. Another package is causing the error.
