### ISSUE TITLE
Error with debug_object

### ISSUE THREAD

**Issue by vineetgoel** [andymccurdy/redis-py#803]
Getting the following error when using the debug_object function of the Redis client:

```
r.debug_object("my_key")

/home/env/local/lib/python2.7/site-packages/redis/client.pyc in debug_object(self, key)
    630     def debug_object(self, key):
    631         "Returns version specific meta information about a given key"
--> 632         return self.execute_command('DEBUG OBJECT', key)
    633
    634     def echo(self, value):

/home/env/local/lib/python2.7/site-packages/redis/client.pyc in execute_command(self, *args, **options)
    563         try:
    564             connection.send_command(*args)
--> 565             return self.parse_response(connection, command_name, **options)
    566         except (ConnectionError, TimeoutError) as e:
    567             connection.disconnect()

/home/env/local/lib/python2.7/site-packages/redis/client.pyc in parse_response(self, connection, command_name, **options)
    575     def parse_response(self, connection, command_name, **options):
    576         "Parses a response from the Redis server"
--> 577         response = connection.read_response()
    578         if command_name in self.response_callbacks:
    579             return self.response_callbacks[command_name](response, **options)

/home/env/local/lib/python2.7/site-packages/redis/connection.pyc in read_response(self)
    572             raise
    573         if isinstance(response, ResponseError):
--> 574             raise response
    575         return response
    576

ResponseError: unknown command 'DEBUG'
```

**Comment by Grokzen** [comment]
@andymccurdy This issue seems to be resolved and issue can be closed. Tested this code and it behaves properly now on redis-py 2.10.6 in py 2.7 env.
```
>>> r.debug_object('bar')                                                                                                    
Traceback (most recent call last):                                                                                           
  File "<stdin>", line 1, in <module>                                                                                        
  File "/home/grok/.virtualenvs/redis-py-cluster/lib/python3.6/site-packages/redis/client.py", line 735, in debug_object     
    return self.execute_command('DEBUG OBJECT', key)                                                                         
  File "/home/grok/.virtualenvs/redis-py-cluster/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command  
    return self.parse_response(connection, command_name, **options)                                                          
  File "/home/grok/.virtualenvs/redis-py-cluster/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response   
    response = connection.read_response()                                                                                    
  File "/home/grok/.virtualenvs/redis-py-cluster/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response                                                                                                           
redis.exceptions.ResponseError: no such key                                                                                  
no such key                                                                                                                  

>>> r.set('bar', 'foo')                                                                                                                     
True                                                                                                                                        
                                                                                                                                            
>>> r.debug_object('bar')                                                                                                                   
{'type': 'Value', 'at': '0x7f46ccba94a8', 'refcount': 1, 'encoding': 'embstr', 'serializedlength': 4, 'lru': 2419631, 'lru_seconds_idle': 1}
```

**Comment by andymccurdy** [comment]
Thanks!
