### ISSUE TITLE
Wrontype Operation when fetching values from hash ?

### ISSUE THREAD

**Issue by johaven** [andymccurdy/redis-py#864]
I don't understand this behaviour, can anyone help me ?
redis version: 3.2.9

```python
for key in r.scan_iter('1:*'):
    print(r.hgetall(key))
    
{b'status': b'2', b'type': b'zip', b'elements': b'0', b'size': b'0', b'id': b'ea81cfa2-575a-4f6a-9701-fba1d55cf3d3', b'started': b'2017-05-28 16:14:33.528618', b'result': b'/tmp/tmpgzyao5na.zip', b'ended': b'2017-05-28 16:14:33.533190'}

Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File ".virtualenvs/web2/lib/python3.6/site-packages/redis/client.py", line 1861, in hgetall
    return self.execute_command('HGETALL', name)
  File ".virtualenvs/web2/lib/python3.6/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File ".virtualenvs/web2/lib/python3.6/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File ".virtualenvs/web2/lib/python3.6/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```

**Comment by johaven** [comment]
ok, one of my keys doesn't have a hash ... sorry :)
