### ISSUE TITLE
Exception when trying to geopos on a non existing location

### ISSUE THREAD

**Issue by edibusl** [andymccurdy/redis-py#890]
redis-py version 2.10.5
redis version 3.2.8

When trying to run the following code, the last line will raise an exception:

```
redis_client = redis.StrictRedis()
redis_client.geopos("mykey", 'location1')
redis_client.geoadd("mykey", 34.8862878, 32.1779851, "location2")
redis_client.geopos("mykey", 'location1')
```

Error:
```
Traceback (most recent call last):
  File "/home/edi/code/fleetenv/lib/python3.5/site-packages/redis/client.py", line 2890, in execute
    return execute(conn, stack, raise_on_error)
  File "/home/edi/code/fleetenv/lib/python3.5/site-packages/redis/client.py", line 2827, in _execute_pipeline
    self.parse_response(connection, args[0], **options))
  File "/home/edi/code/fleetenv/lib/python3.5/site-packages/redis/client.py", line 2849, in parse_response
    self, connection, command_name, **options)
  File "/home/edi/code/fleetenv/lib/python3.5/site-packages/redis/client.py", line 681, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "/home/edi/code/fleetenv/lib/python3.5/site-packages/redis/client.py", line 451, in <lambda>
    float(ll[1])), r)),
  File "/home/edi/code/fleetenv/lib/python3.5/site-packages/redis/client.py", line 450, in <lambda>
    'GEOPOS': lambda r: list(map(lambda ll: (float(ll[0]),
TypeError: 'NoneType' object is not subscriptable
```

**Comment by andymccurdy** [comment]
I believe this was just fixed and merged yesterday. Could you try using the code in master in your environment and confirm please?

**Comment by edibusl** [comment]
It works in master. Thanks!
When will it be available in pip?

**Comment by andymccurdy** [comment]
2.10.6 is on PyPI now!
