### ISSUE TITLE
unknown command set

### ISSUE THREAD

**Issue by River-Mountain** [andymccurdy/redis-py#892]
pool = redis.ConnectionPool(host='192.168.1.153', port=26379, db=0)
r = redis.Redis(connection_pool=pool)
r.set("foo", "bar")

this is my code, however I get the error ：
Traceback (most recent call last):
  File "/Users/mountain/PycharmProjects/news_crawler/toutiaohao_crawler/test.py", line 6, in <module>
    r.set("foo", "bar")
  File "/Users/mountain/anaconda/lib/python3.6/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/Users/mountain/anaconda/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/mountain/anaconda/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/mountain/anaconda/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'SET'

**Comment by andymccurdy** [comment]
It looks like you're connecting to a Redis Sentinel server rather than the Redis server itself. If you're using Sentinel in your environment, you should refer to the docs here: https://github.com/andymccurdy/redis-py#sentinel-support

**Comment by andymccurdy** [comment]
Closing this as I believe it's user error. Please feel free to re-open if you're still having issues.

**Comment by kuraga** [comment]
>  If you're using Sentinel in your environment, you should refer to the docs here: https://github.com/andymccurdy/redis-py#sentinel-support

@andymccurdy what could you mean here? Because connection techniques discussed there not set of commands...
