### ISSUE TITLE
when using pipe raise AttributeError!

### ISSUE THREAD

**Issue by ltgo** [andymccurdy/redis-py#901]
below is my code:
>>> r = redis.Redis(host, port)
>>> p = r.pipeline()
>>> p.set('foo','bar')
Pipeline<ConnectionPool<Connection<host=10.49.102.208,port=9006,db=0>>>
>>> p.set('bing','bbb')
Pipeline<ConnectionPool<Connection<host=10.49.102.208,port=9006,db=0>>>
>>> p.execute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/news/arioliu/qps_test/env/lib/python2.7/site-packages/redis/client.py", line 2879, in execute
    return execute(conn, stack, raise_on_error)
  File "/data/news/arioliu/qps_test/env/lib/python2.7/site-packages/redis/client.py", line 2785, in _execute_transaction
    response.insert(i, e)
AttributeError: 'str' object has no attribute 'insert'

when i use p = r.pipeline(transaction=False),  it is ok!

**Comment by andymccurdy** [comment]
What version of redis-py and redis are you using?

I've run your exact code block locally it works as expected.
