### ISSUE TITLE
Bench command_packer_benchmark.py not work

### ISSUE THREAD

**Issue by deslum** [andymccurdy/redis-py#979]
**python command_packer_benchmark.py**
 
```
Benchmark: connection_class=<class '__main__.StringJoiningConnection'>, value_size=10... Traceback (most recent call last):
  File "command_packer_benchmark.py", line 104, in <module>
    CommandPackerBenchmark().run_benchmark()
  File "/home/deslum/src/cgo/redis/redis-py/benchmarks/base.py", line 44, in run_benchmark
    t = timeit.timeit(stmt=run, setup=setup, number=1000)
  File "/usr/lib/python2.7/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer).timeit(number)
  File "/usr/lib/python2.7/timeit.py", line 202, in timeit
    timing = self.inner(it, self.timer)
  File "/usr/lib/python2.7/timeit.py", line 100, in inner
    _func()
  File "command_packer_benchmark.py", line 100, in run
    r.set('benchmark', x)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "command_packer_benchmark.py", line 33, in pack_command
    for k in imap(self.encoder, args)])
TypeError: 'Encoder' object is not callable
```

**python3 command_packer_benchmark.py** 

```
Benchmark: connection_class=<class '__main__.StringJoiningConnection'>, value_size=10... Traceback (most recent call last):
  File "command_packer_benchmark.py", line 104, in <module>
    CommandPackerBenchmark().run_benchmark()
  File "/home/deslum/src/cgo/redis/redis-py/benchmarks/base.py", line 44, in run_benchmark
    t = timeit.timeit(stmt=run, setup=setup, number=1000)
  File "/usr/lib/python3.5/timeit.py", line 213, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/usr/lib/python3.5/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "command_packer_benchmark.py", line 100, in run
    r.set('benchmark', x)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "command_packer_benchmark.py", line 33, in pack_command
    for k in imap(self.encode, args)])
AttributeError: 'StringJoiningConnection' object has no attribute 'encode'
```
pip

```
Package    Version
---------- -------
hiredis    0.2.0  
pip        10.0.1 
redis      2.10.6 
setuptools 39.2.0 
wheel      0.31.1 
```

**Comment by deslum** [comment]
Fixed
