### ISSUE TITLE
hmset of 25mb object gives - Error 32 while writing to socket. Broken pipe.

### ISSUE THREAD

**Issue by jonathan-kosgei** [andymccurdy/redis-py#986]
I have
```
data = {} # 25mb dict
test = redis.Redis(host='127.0.0.1', port=6379, db=15, decode_responses=True)
test.hmset('usage', data)
```

But get

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 590, in send_packed_command
    self._sock.sendall(item)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 603, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.
```

**Comment by jonathan-kosgei** [comment]
@andymccurdy I still have this issue, `hmset` fails with a dict of any significant size eg. 400k

**Comment by andymccurdy** [comment]
I'm going to close this as there are reasonable work arounds by batch loading data. If someone authors a patch to improves redis-py's ability to handle larger amounts of data, I'll gladly take a look at it.
