### ISSUE TITLE
KeyError on repr in any ConnectionPool without host/port/db arguments

### ISSUE THREAD

**Issue by carsonip** [andymccurdy/redis-py#995]
To reproduce:
```
import redis
p = redis.ConnectionPool()
repr(p)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "venv/local/lib/python2.7/site-packages/redis/connection.py", line 939, in __repr__
    self.connection_class.description_format % self.connection_kwargs,
KeyError: 'host'
```

`connection_kwargs` does not require `host`, `port` and `db` but `repr()` requires it and will crash on call.

**Comment by michaelDovgal** [comment]
Just wanted to open the same issue. 
Also this issue going to StrictRedis objects.

```
>>> import redis
>>> pool = redis.ConnectionPool(host='fake_host', port=6379, password=None)
>>> redis_cli = redis.Redis(connection_pool=pool)
>>> redis_cli
*** KeyError: 'db'

```

**Comment by GitHubMota** [comment]
This issue also trouble me. Wish to be fix.

**Comment by jedie** [comment]
think i have the same problem:
```
    def __repr__(self):
        return "%s<%s>" % (
            type(self).__name__,
>           self.connection_class.description_format % self.connection_kwargs,
        )
E       KeyError: 'db'

self       = <[KeyError("'db'") raised in repr()] ConnectionPool object at 0x7fa4f78192b0>

/usr/local/lib/python3.6/site-packages/redis/connection.py:944: KeyError
```
isn't it?

Happens with `redis==3.0.1`
